import {createContext,useContext,useEffect,useMemo,useState} from 'react';
export const locales=['vi','en'];
export const localeNames={vi:'Tiếng Việt',en:'English'};
const D={
vi:{home:'Trang chủ',guide:'Hướng dẫn',dashboard:'Bảng điều khiển',commands:'Lệnh',news:'Tin tức',forum:'Diễn đàn',support:'Hỗ trợ',review:'Duyệt Market',admin:'Quản trị',profile:'Hồ sơ',login:'Đăng nhập',addBot:'Thêm bot',official:'CỘNG ĐỒNG CHÍNH THỨC',about:'Giới thiệu',terms:'Điều khoản',privacy:'Quyền riêng tư',footer:'Website chính thức & cộng đồng Corgi-Bot — Game Hub, CXu, Marketplace, Event, Clan và hỗ trợ.',present:'Corgi Studio giới thiệu',hero1:'Một bot.',hero2:'Cả hệ sinh thái Discord.',heroP:'Quản lý server, Game Hub, Pet Hunt, Startup, Fishing, CXu, sự kiện và cộng đồng trong một trải nghiệm thống nhất.',viewCommands:'Xem lệnh',online:'Bot online',topics:'Chủ đề forum',basicAi:'AI tích hợp',ready:'Corgi-Bot V10 sẵn sàng cho server của bạn',community:'Cộng đồng Corgi-Bot',communityItems:'Game Hub · Event · Creator · Clan · Community',features:'V10 ECOSYSTEM',featuresTitle:'Không chỉ quản lý server — còn có cả một Game Hub.',communityTitle:'Cộng đồng và tiến trình ở cùng một nơi.',communityP:'Theo dõi tin mới, tham gia diễn đàn, quản lý profile, sự kiện, clan và các hệ thống kết nối với bot.',latest:'TIN MỚI NHẤT',noArticle:'Chưa có bài viết',adminPost:'Admin có thể đăng bài từ Control Panel.',readNews:'Đọc tin tức →',forumTitle:'DIỄN ĐÀN',forumCount:'chủ đề cộng đồng.',forumP:'Tạo topic, trả lời và trao đổi bằng tài khoản Discord.',goForum:'Vào diễn đàn →',start:'BẮT ĐẦU',startTitle:'Sẵn sàng đưa Corgi-Bot vào server?',startP:'Thêm bot và mở /help hoặc /game để bắt đầu.',addDiscord:'Thêm bot vào Discord',cmdTitle:'Lệnh Corgi-Bot V10',cmdP:'Danh mục lệnh của phiên bản Corgi-Bot hiện tại.',search:'Tìm lệnh…',loading:'Đang tải lệnh…',cmdCount:'lệnh',language:'Ngôn ngữ',games:'Game Hub'},
en:{home:'Home',guide:'Guide',dashboard:'Dashboard',commands:'Commands',news:'News',forum:'Forum',support:'Support',review:'Market Review',admin:'Admin',profile:'Profile',login:'Log in',addBot:'Add bot',official:'OFFICIAL COMMUNITY',about:'About',terms:'Terms',privacy:'Privacy',footer:'Official Corgi-Bot website & community — Game Hub, CXu, Marketplace, Events, Clan and support.',present:'Corgi Studio presents',hero1:'One bot.',hero2:'A complete Discord ecosystem.',heroP:'Server management, Game Hub, Pet Hunt, Startup, Fishing, CXu, events and community in one connected experience.',viewCommands:'View commands',online:'Bot online',topics:'Forum topics',basicAi:'Integrated AI',ready:'Corgi-Bot V10 is ready for your server',community:'Corgi-Bot Community',communityItems:'Game Hub · Events · Creator · Clan · Community',features:'V10 ECOSYSTEM',featuresTitle:'More than server management — a complete Game Hub.',communityTitle:'Community and progression in one place.',communityP:'Follow updates, join the forum, manage your profile, events, clan and bot-connected systems.',latest:'LATEST NEWS',noArticle:'No articles yet',adminPost:'Admins can publish from the Control Panel.',readNews:'Read news →',forumTitle:'FORUM',forumCount:'community topics.',forumP:'Create topics, reply and chat with your Discord account.',goForum:'Open forum →',start:'START NOW',startTitle:'Ready to add Corgi-Bot to your server?',startP:'Add the bot and open /help or /game to get started.',addDiscord:'Add bot to Discord',cmdTitle:'Corgi-Bot V10 Commands',cmdP:'Command directory for the current Corgi-Bot release.',search:'Search commands…',loading:'Loading commands…',cmdCount:'commands',language:'Language',games:'Game Hub'}};
const C=createContext(null);
export function I18nProvider({children}){const [locale,setLocaleState]=useState(()=>{const x=localStorage.getItem('corgi_locale');return locales.includes(x)?x:'vi'});const setLocale=x=>setLocaleState(locales.includes(x)?x:'vi');useEffect(()=>{localStorage.setItem('corgi_locale',locale);document.documentElement.lang=locale},[locale]);const value=useMemo(()=>({locale,setLocale,t:(k)=>D[locale]?.[k]??D.en[k]??k}),[locale]);return <C.Provider value={value}>{children}</C.Provider>}
export const useI18n=()=>useContext(C);
