import {createContext,useContext,useEffect,useMemo,useState} from 'react';

export const locales=['en','vi','pt-BR','pt-PT','es','fr','de','ja','ko','id','zh-TW','zh-CN'];
export const localeNames={en:'English',vi:'Tiếng Việt','pt-BR':'Português (BR)','pt-PT':'Português (PT)',es:'Español',fr:'Français',de:'Deutsch',ja:'日本語',ko:'한국어',id:'Bahasa Indonesia','zh-TW':'繁體中文','zh-CN':'简体中文'};
const D={
 en:{home:'Home',dashboard:'Dashboard',commands:'Commands',news:'News',forum:'Forum',bank:'Bank',market:'Market',ads:'Ads',premium:'Premium',support:'Support',review:'Market Review',admin:'Admin',profile:'Profile',login:'Log in',addBot:'Add bot',official:'OFFICIAL COMMUNITY',about:'About',terms:'Terms',privacy:'Privacy',footer:'Official Corgi-Bot website & community — CXu Bank, Marketplace, CToken Ads, news, forum and support.',present:'Corgi Studio presents',hero1:'Smarter server management.',hero2:'More fun for everyone.',heroP:'Corgi-Bot brings moderation, AI, levels, economy, giveaways and contests into one easy ecosystem for your Discord server.',viewCommands:'View commands',online:'Bot online',topics:'Forum topics',basicAi:'Basic AI',ready:'Corgi-Bot is always ready for your server',community:'Corgi-Bot Community',communityItems:'News · Forum · Support · Members',features:'FEATURES',featuresTitle:'Everything your server needs, in one bot.',communityTitle:'A dedicated space for the Corgi-Bot community.',communityP:'Follow updates, join discussions, share feedback and get support whenever you need it.',latest:'LATEST NEWS',noArticle:'No articles yet',adminPost:'Admins can publish from the Control Panel.',readNews:'Read news →',forumTitle:'FORUM',forumCount:'community topics.',forumP:'Create topics, reply and chat with your Discord account.',goForum:'Open forum →',start:'START NOW',startTitle:'Ready to add Corgi-Bot to your server?',startP:'Add the bot, run /setup and configure each module.',addDiscord:'Add bot to Discord',cmdTitle:'Corgi-Bot Commands',cmdP:'Complete command directory for the current Corgi-Bot experience.',search:'Search commands…',loading:'Loading commands…',cmdCount:'commands',language:'Language'},
 vi:{home:'Trang chủ',dashboard:'Bảng điều khiển',commands:'Lệnh',news:'Tin tức',forum:'Diễn đàn',bank:'Bank',market:'Market',ads:'Ads',premium:'Premium',support:'Hỗ trợ',review:'Duyệt Market',admin:'Quản trị',profile:'Hồ sơ',login:'Đăng nhập',addBot:'Thêm bot',official:'CỘNG ĐỒNG CHÍNH THỨC',about:'Giới thiệu',terms:'Điều khoản',privacy:'Quyền riêng tư',footer:'Website chính thức & cộng đồng của Corgi-Bot — CXu Bank, Marketplace, CToken Ads, tin tức, diễn đàn và hỗ trợ.',present:'Corgi Studio giới thiệu',hero1:'Quản lý server gọn hơn.',hero2:'Cộng đồng vui hơn.',heroP:'Corgi-Bot mang các công cụ quản lý, AI, level, economy, giveaway và contest vào một hệ sinh thái dễ dùng cho server Discord của bạn.',viewCommands:'Xem lệnh',online:'Bot online',topics:'Chủ đề forum',basicAi:'AI cơ bản',ready:'Corgi-Bot luôn sẵn sàng đồng hành cùng server',community:'Cộng đồng Corgi-Bot',communityItems:'Tin tức · Diễn đàn · Hỗ trợ · Thành viên',features:'TÍNH NĂNG',featuresTitle:'Mọi thứ server cần, tập trung trong một bot.',communityTitle:'Không gian dành riêng cho cộng đồng Corgi-Bot.',communityP:'Theo dõi tin mới, tham gia thảo luận, chia sẻ ý kiến và nhận hỗ trợ khi bạn cần.',latest:'TIN MỚI NHẤT',noArticle:'Chưa có bài viết',adminPost:'Admin có thể đăng bài từ Control Panel.',readNews:'Đọc tin tức →',forumTitle:'DIỄN ĐÀN',forumCount:'chủ đề cộng đồng.',forumP:'Tạo topic, trả lời và trao đổi bằng tài khoản Discord.',goForum:'Vào diễn đàn →',start:'BẮT ĐẦU',startTitle:'Sẵn sàng đưa Corgi-Bot vào server?',startP:'Thêm bot, chạy /setup và bắt đầu cấu hình từng module.',addDiscord:'Thêm bot vào Discord',cmdTitle:'Lệnh Corgi-Bot',cmdP:'Danh mục lệnh đầy đủ cho phiên bản Corgi-Bot hiện tại.',search:'Tìm lệnh…',loading:'Đang tải lệnh…',cmdCount:'lệnh',language:'Ngôn ngữ'},
 es:{home:'Inicio',dashboard:'Panel',commands:'Comandos',news:'Noticias',forum:'Foro',support:'Soporte',review:'Revisar Market',admin:'Administración',profile:'Perfil',login:'Iniciar sesión',addBot:'Añadir bot',about:'Acerca de',terms:'Términos',privacy:'Privacidad',hero1:'Gestiona tu servidor mejor.',hero2:'Una comunidad más divertida.',viewCommands:'Ver comandos',online:'Bot en línea',topics:'Temas del foro',basicAi:'IA básica',cmdTitle:'Comandos de Corgi-Bot',cmdP:'Directorio completo de comandos de Corgi-Bot.',search:'Buscar comandos…',loading:'Cargando comandos…',cmdCount:'comandos',language:'Idioma'},
 fr:{home:'Accueil',dashboard:'Tableau de bord',commands:'Commandes',news:'Actualités',forum:'Forum',support:'Support',review:'Révision Market',admin:'Administration',profile:'Profil',login:'Connexion',addBot:'Ajouter le bot',about:'À propos',terms:'Conditions',privacy:'Confidentialité',hero1:'Gérez mieux votre serveur.',hero2:'Une communauté plus fun.',viewCommands:'Voir les commandes',online:'Bot en ligne',topics:'Sujets du forum',basicAi:'IA de base',cmdTitle:'Commandes Corgi-Bot',cmdP:'Répertoire complet des commandes Corgi-Bot.',search:'Rechercher une commande…',loading:'Chargement…',cmdCount:'commandes',language:'Langue'},
 de:{home:'Start',dashboard:'Dashboard',commands:'Befehle',news:'News',forum:'Forum',support:'Support',review:'Market prüfen',admin:'Verwaltung',profile:'Profil',login:'Anmelden',addBot:'Bot hinzufügen',about:'Über uns',terms:'Bedingungen',privacy:'Datenschutz',hero1:'Server einfacher verwalten.',hero2:'Mehr Spaß für alle.',viewCommands:'Befehle ansehen',online:'Bot online',topics:'Forum-Themen',basicAi:'Basis-KI',cmdTitle:'Corgi-Bot Befehle',cmdP:'Vollständiges Befehlsverzeichnis für Corgi-Bot.',search:'Befehle suchen…',loading:'Befehle werden geladen…',cmdCount:'Befehle',language:'Sprache'},
 id:{home:'Beranda',dashboard:'Dasbor',commands:'Perintah',news:'Berita',forum:'Forum',support:'Dukungan',review:'Tinjau Market',admin:'Admin',profile:'Profil',login:'Masuk',addBot:'Tambah bot',about:'Tentang',terms:'Ketentuan',privacy:'Privasi',hero1:'Kelola server lebih mudah.',hero2:'Komunitas lebih seru.',viewCommands:'Lihat perintah',online:'Bot online',topics:'Topik forum',basicAi:'AI dasar',cmdTitle:'Perintah Corgi-Bot',cmdP:'Direktori lengkap perintah Corgi-Bot.',search:'Cari perintah…',loading:'Memuat perintah…',cmdCount:'perintah',language:'Bahasa'},
 ja:{home:'ホーム',dashboard:'ダッシュボード',commands:'コマンド',news:'ニュース',forum:'フォーラム',support:'サポート',review:'マーケット審査',admin:'管理',profile:'プロフィール',login:'ログイン',addBot:'Botを追加',about:'概要',terms:'利用規約',privacy:'プライバシー',hero1:'サーバー管理をもっとスマートに。',hero2:'コミュニティをもっと楽しく。',viewCommands:'コマンドを見る',online:'Botオンライン',topics:'フォーラムトピック',basicAi:'基本AI',cmdTitle:'Corgi-Bot コマンド',cmdP:'Corgi-Bot の完全なコマンド一覧です。',search:'コマンドを検索…',loading:'読み込み中…',cmdCount:'コマンド',language:'言語'},
 ko:{home:'홈',dashboard:'대시보드',commands:'명령어',news:'뉴스',forum:'포럼',support:'지원',review:'마켓 검토',admin:'관리',profile:'프로필',login:'로그인',addBot:'봇 추가',about:'소개',terms:'이용약관',privacy:'개인정보',hero1:'서버 관리를 더 간편하게.',hero2:'커뮤니티를 더 즐겁게.',viewCommands:'명령어 보기',online:'봇 온라인',topics:'포럼 주제',basicAi:'기본 AI',cmdTitle:'Corgi-Bot 명령어',cmdP:'현재 Corgi-Bot의 전체 명령어 목록입니다.',search:'명령어 검색…',loading:'명령어 불러오는 중…',cmdCount:'명령어',language:'언어'},
 'pt-BR':{home:'Início',dashboard:'Painel',commands:'Comandos',news:'Notícias',forum:'Fórum',support:'Suporte',review:'Revisar Market',admin:'Administração',profile:'Perfil',login:'Entrar',addBot:'Adicionar bot',about:'Sobre',terms:'Termos',privacy:'Privacidade',hero1:'Gerencie seu servidor melhor.',hero2:'Comunidade mais divertida.',viewCommands:'Ver comandos',online:'Bot online',topics:'Tópicos do fórum',basicAi:'IA básica',cmdTitle:'Comandos do Corgi-Bot',cmdP:'Diretório completo de comandos do Corgi-Bot.',search:'Buscar comandos…',loading:'Carregando comandos…',cmdCount:'comandos',language:'Idioma'},
 'pt-PT':{home:'Início',dashboard:'Painel',commands:'Comandos',news:'Notícias',forum:'Fórum',support:'Suporte',review:'Rever Market',admin:'Administração',profile:'Perfil',login:'Entrar',addBot:'Adicionar bot',about:'Sobre',terms:'Termos',privacy:'Privacidade',hero1:'Gere o servidor de forma mais simples.',hero2:'Uma comunidade mais divertida.',viewCommands:'Ver comandos',online:'Bot online',topics:'Tópicos do fórum',basicAi:'IA básica',cmdTitle:'Comandos Corgi-Bot',cmdP:'Diretório completo de comandos do Corgi-Bot.',search:'Pesquisar comandos…',loading:'A carregar comandos…',cmdCount:'comandos',language:'Idioma'},
 'zh-TW':{home:'首頁',dashboard:'控制台',commands:'指令',news:'新聞',forum:'論壇',support:'支援',review:'市集審核',admin:'管理',profile:'個人資料',login:'登入',addBot:'新增 Bot',about:'關於',terms:'條款',privacy:'隱私',hero1:'更輕鬆地管理伺服器。',hero2:'讓社群更有趣。',viewCommands:'查看指令',online:'Bot 在線',topics:'論壇主題',basicAi:'基礎 AI',cmdTitle:'Corgi-Bot 指令',cmdP:'目前 Corgi-Bot 的完整指令目錄。',search:'搜尋指令…',loading:'載入指令中…',cmdCount:'個指令',language:'語言'},
 'zh-CN':{home:'首页',dashboard:'控制台',commands:'命令',news:'新闻',forum:'论坛',support:'支持',review:'市场审核',admin:'管理',profile:'个人资料',login:'登录',addBot:'添加 Bot',about:'关于',terms:'条款',privacy:'隐私',hero1:'更轻松地管理服务器。',hero2:'让社区更有趣。',viewCommands:'查看命令',online:'Bot 在线',topics:'论坛主题',basicAi:'基础 AI',cmdTitle:'Corgi-Bot 命令',cmdP:'当前 Corgi-Bot 的完整命令目录。',search:'搜索命令…',loading:'正在加载命令…',cmdCount:'个命令',language:'语言'}
};
const C=createContext(null);
export function I18nProvider({children}){const [locale,setLocale]=useState(()=>localStorage.getItem('corgi_locale')||'vi');useEffect(()=>{localStorage.setItem('corgi_locale',locale);document.documentElement.lang=locale},[locale]);const value=useMemo(()=>({locale,setLocale,t:(k)=>D[locale]?.[k]??D.en[k]??k}),[locale]);return <C.Provider value={value}>{children}</C.Provider>}
export const useI18n=()=>useContext(C);
