import {createContext,useContext,useEffect,useMemo,useState} from 'react';

export const locales=['vi','en'];
export const localeNames={vi:'Tiếng Việt',en:'English'};
const D={
 en:{home:'Home',guide:'Guide',dashboard:'Dashboard',commands:'Commands',news:'News',forum:'Forum',bank:'Bank',market:'Market',ads:'Ads',premium:'Premium',support:'Support',review:'Market Review',admin:'Admin',profile:'Profile',login:'Log in',addBot:'Add bot',official:'OFFICIAL COMMUNITY',about:'About',terms:'Terms',privacy:'Privacy',footer:'Official Corgi-Bot website & community — CXu Bank, Marketplace, CToken Ads, news, forum and support.',present:'Corgi Studio presents',hero1:'Smarter server management.',hero2:'More fun for everyone.',heroP:'Corgi-Bot brings moderation, AI, levels, economy, giveaways and contests into one easy ecosystem for your Discord server.',viewCommands:'View commands',online:'Bot online',topics:'Forum topics',basicAi:'Basic AI',ready:'Corgi-Bot is always ready for your server',community:'Corgi-Bot Community',communityItems:'News · Forum · Support · Members',features:'FEATURES',featuresTitle:'Everything your server needs, in one bot.',communityTitle:'A dedicated space for the Corgi-Bot community.',communityP:'Follow updates, join discussions, share feedback and get support whenever you need it.',latest:'LATEST NEWS',noArticle:'No articles yet',adminPost:'Admins can publish from the Control Panel.',readNews:'Read news →',forumTitle:'FORUM',forumCount:'community topics.',forumP:'Create topics, reply and chat with your Discord account.',goForum:'Open forum →',start:'START NOW',startTitle:'Ready to add Corgi-Bot to your server?',startP:'Add the bot, run /setup and configure each module.',addDiscord:'Add bot to Discord',cmdTitle:'Corgi-Bot Commands',cmdP:'Complete command directory for the current Corgi-Bot experience.',search:'Search commands…',loading:'Loading commands…',cmdCount:'commands',language:'Language'},
 vi:{home:'Trang chủ',guide:'Hướng dẫn',dashboard:'Bảng điều khiển',commands:'Lệnh',news:'Tin tức',forum:'Diễn đàn',bank:'Bank',market:'Market',ads:'Ads',premium:'Premium',support:'Hỗ trợ',review:'Duyệt Market',admin:'Quản trị',profile:'Hồ sơ',login:'Đăng nhập',addBot:'Thêm bot',official:'CỘNG ĐỒNG CHÍNH THỨC',about:'Giới thiệu',terms:'Điều khoản',privacy:'Quyền riêng tư',footer:'Website chính thức & cộng đồng của Corgi-Bot — CXu Bank, Marketplace, CToken Ads, tin tức, diễn đàn và hỗ trợ.',present:'Corgi Studio giới thiệu',hero1:'Quản lý server gọn hơn.',hero2:'Cộng đồng vui hơn.',heroP:'Corgi-Bot mang các công cụ quản lý, AI, level, economy, giveaway và contest vào một hệ sinh thái dễ dùng cho server Discord của bạn.',viewCommands:'Xem lệnh',online:'Bot online',topics:'Chủ đề forum',basicAi:'AI cơ bản',ready:'Corgi-Bot luôn sẵn sàng đồng hành cùng server',community:'Cộng đồng Corgi-Bot',communityItems:'Tin tức · Diễn đàn · Hỗ trợ · Thành viên',features:'TÍNH NĂNG',featuresTitle:'Mọi thứ server cần, tập trung trong một bot.',communityTitle:'Không gian dành riêng cho cộng đồng Corgi-Bot.',communityP:'Theo dõi tin mới, tham gia thảo luận, chia sẻ ý kiến và nhận hỗ trợ khi bạn cần.',latest:'TIN MỚI NHẤT',noArticle:'Chưa có bài viết',adminPost:'Admin có thể đăng bài từ Control Panel.',readNews:'Đọc tin tức →',forumTitle:'DIỄN ĐÀN',forumCount:'chủ đề cộng đồng.',forumP:'Tạo topic, trả lời và trao đổi bằng tài khoản Discord.',goForum:'Vào diễn đàn →',start:'BẮT ĐẦU',startTitle:'Sẵn sàng đưa Corgi-Bot vào server?',startP:'Thêm bot, chạy /setup và bắt đầu cấu hình từng module.',addDiscord:'Thêm bot vào Discord',cmdTitle:'Lệnh Corgi-Bot',cmdP:'Danh mục lệnh đầy đủ cho phiên bản Corgi-Bot hiện tại.',search:'Tìm lệnh…',loading:'Đang tải lệnh…',cmdCount:'lệnh',language:'Ngôn ngữ'}
};
const C=createContext(null);
export function I18nProvider({children}){const [locale,setLocale]=useState(()=>{const saved=localStorage.getItem('corgi_locale');return locales.includes(saved)?saved:'vi'});useEffect(()=>{localStorage.setItem('corgi_locale',locale);document.documentElement.lang=locale},[locale]);const value=useMemo(()=>({locale,setLocale,t:(k)=>D[locale]?.[k]??D.en[k]??k}),[locale]);return <C.Provider value={value}>{children}</C.Provider>}
export const useI18n=()=>useContext(C);
