import { useEffect, useMemo, useState } from 'react';
import { BarChart3, Megaphone, MousePointerClick, Plus, Timer, XCircle } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { botApi, botApiConfigured } from '../lib/botApi';
import { ErrorState, LoadingState } from '../components/ApiState';
import { useI18n } from '../i18n/index.jsx';
import { compactNumber } from '../lib/numberFormat';
const placements={HOME:'Home',TRENDING:'Trending',VOTE:'Vote',GAME_HUB:'Game Hub',MARKETPLACE:'Marketplace',LEADERBOARD:'Leaderboard',PROFILE:'Profile',NEWS_FORUM:'News & Forum',NETWORK:'Network'};const n=compactNumber;
const vi={center:'Trung tâm quảng cáo',intro:'Quảng bá trực tiếp vật phẩm đang bán trên Market bằng CToken.',new:'TẠO QUẢNG CÁO MARKET',product:'Vật phẩm quảng cáo',productHelp:'Chỉ chọn sản phẩm đang có sẵn trên Creator Market.',where:'Vị trí hiển thị',desc:'Mô tả quảng cáo',descPh:'Viết một mô tả ngắn hấp dẫn cho vật phẩm.',budget:'Ngân sách CToken',budgetHelp:'Tự nhập số CToken bạn muốn chi cho chiến dịch.',days:'Thời gian chạy',daysHelp:'Chọn nhanh hoặc nhập số ngày bạn muốn chạy.',preview:'Xem trước quảng cáo',previewEmpty:'Chọn một vật phẩm Market để xem trước.',create:'Tạo quảng cáo',creating:'Đang tạo…',history:'Lịch sử chiến dịch',none:'Bạn chưa có chiến dịch quảng cáo.',active:'Đang chạy',cancelled:'Đã hủy',ended:'Đã kết thúc',analytics:'Thống kê',cancel:'Hủy',login:'Đăng nhập Discord để quảng bá vật phẩm Market bằng CToken.',loginBtn:'Đăng nhập',created:'Chiến dịch Market Ads đã được tạo.',marketEmpty:'Chưa có vật phẩm Market phù hợp để quảng cáo.'};
const en={...vi,center:'Advertising Center',intro:'Promote an existing Market item with CToken.',new:'NEW MARKET AD',product:'Product to promote',productHelp:'Choose an existing product from Creator Market.',where:'Display location',desc:'Ad description',descPh:'Write a short, appealing description for this product.',budget:'CToken budget',budgetHelp:'Enter the amount of CToken you want to spend on this campaign.',days:'Run time',daysHelp:'Choose a preset or enter the number of days.',preview:'Ad preview',previewEmpty:'Choose a Market item to preview it.',create:'Create ad',creating:'Creating…',history:'Campaign history',none:'You have no ad campaigns yet.',active:'Active',cancelled:'Cancelled',ended:'Ended',analytics:'Analytics',cancel:'Cancel',login:'Log in with Discord to promote Market items using CToken.',loginBtn:'Log in',created:'Market Ads campaign created.',marketEmpty:'No eligible Market products are available.'};
const dayPresets=[1,3,7,30];
function productData(row){const x=row?.cosmetic||row?.item||row||{};return {id:row?._id||x?._id||'',name:x.name||row?.name||'Market item',creator:x.creatorName||row?.creatorName||'',type:String(x.type||row?.type||'').toUpperCase(),image:['FRAME','BACKGROUND'].includes(String(x.type||'').toUpperCase())?String(x.value||''):String(row?.imageUrl||x.imageUrl||''),price:Number(row?.price||x.price||0),raw:row}}
export default function Ads(){const {locale}=useI18n();const c=locale==='vi'?vi:en;const {user,session}=useAuth();const token=session?.access_token;const [items,setItems]=useState([]),[market,setMarket]=useState([]),[analytics,setAnalytics]=useState(null),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');const [form,setForm]=useState({marketplaceId:'',description:'',placement:'HOME',budget:'5',days:'1'});const days=Math.max(1,Number(form.days||1)),budget=Math.max(1,Number(form.budget||1));const product=useMemo(()=>market.map(productData).find(x=>x.id===form.marketplaceId),[market,form.marketplaceId]);
 async function load(){if(!token)return;setError('');try{const [mine,shop]=await Promise.all([botApi.adsMine(token),botApi.marketplace()]);setItems(mine?.items||[]);setMarket(shop?.items||[])}catch(e){setError(e)}}useEffect(()=>{load()},[token]);
 async function create(e){e.preventDefault();if(!product){setNotice(`❌ ${c.product}`);return}setBusy(true);setNotice('');try{await botApi.adSubmit({marketplaceId:product.id,marketItemId:product.id,productId:product.id,title:product.name,description:form.description,placement:form.placement,days,budget,ctokenPerDay:budget/days,imageUrl:product.image,marketPrice:product.price},token);setNotice(c.created);setForm(v=>({...v,marketplaceId:'',description:'',budget:'5',days:'1'}));await load()}catch(e2){setNotice(`❌ ${e2.message}`)}finally{setBusy(false)}}
 async function cancel(id){if(!confirm(locale==='vi'?'Hủy chiến dịch này? CToken đã thanh toán sẽ không được hoàn lại.':'Cancel this campaign? Paid CToken is not refundable.'))return;setBusy(true);try{await botApi.adCancel(id,token);await load();if(selected===id)setAnalytics(null)}catch(e){setNotice(`❌ ${e.message}`)}finally{setBusy(false)}}
 async function view(id){setSelected(id);setAnalytics(null);try{setAnalytics(await botApi.adAnalytics(id,token))}catch(e){setNotice(`❌ ${e.message}`)}}
 const statusLabel=s=>s==='ACTIVE'?c.active:s==='CANCELLED'?c.cancelled:s==='ENDED'?c.ended:s;
 if(!botApiConfigured)return <section className="section page-section"><ErrorState error="VITE_CORGI_API_URL is not configured."/></section>;if(!user)return <section className="section page-section"><div className="auth-card"><Megaphone/><h1>Corgi Ads</h1><p>{c.login}</p><Link className="btn primary" to="/login">{c.loginBtn}</Link></div></section>;
 return <section className="section page-section"><div className="section-heading"><span>CTOKEN • MARKET ADS</span><h1>{c.center}</h1><p>{c.intro}</p></div><form className="panel-form ads-create" onSubmit={create}><div className="eyebrow"><Plus size={14}/> {c.new}</div>
 <label>{c.product}<small className="field-help">{c.productHelp}</small>{!market.length?<div className="empty-state">{c.marketEmpty}</div>:<select required value={form.marketplaceId} onChange={e=>setForm({...form,marketplaceId:e.target.value})}><option value="">{locale==='vi'?'— Chọn vật phẩm trên Market —':'— Choose a Market item —'}</option>{market.map(row=>{const p=productData(row);return <option key={p.id} value={p.id}>{p.name} • {n(p.price)} CXu{p.creator?` • ${p.creator}`:''}</option>})}</select>}</label>
 <label>{c.where}<select value={form.placement} onChange={e=>setForm({...form,placement:e.target.value})}>{Object.entries(placements).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>{c.desc}<textarea required maxLength="240" rows="3" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder={c.descPh}/></label>
 <label>{c.budget}<input required inputMode="numeric" min="1" max="1000000" value={form.budget} onChange={e=>setForm({...form,budget:e.target.value.replace(/[^0-9]/g,'')})} placeholder="CToken"/><small className="field-help">{c.budgetHelp}</small></label>
 <label>{c.days}<div className="budget-presets">{dayPresets.map(v=><button type="button" key={v} className={`budget-chip ${days===v?'selected':''}`} onClick={()=>setForm({...form,days:String(v)})}>{v} {locale==='vi'?'ngày':'day'}{locale!=='vi'&&v!==1?'s':''}</button>)}</div><input required inputMode="numeric" min="1" max="365" value={form.days} onChange={e=>setForm({...form,days:e.target.value.replace(/[^0-9]/g,'')})}/><small className="field-help">{c.daysHelp}</small></label>
 <div className="ad-preview"><span className="eyebrow">{c.preview}</span>{product?<>{product.image&&<img src={product.image} alt=""/>}<b>{product.name}</b>{product.creator&&<small>by {product.creator}</small>}<small>{n(product.price)} CXu</small>{form.description&&<p>{form.description}</p>}<small>{placements[form.placement]} • {days} {locale==='vi'?'ngày':'day'+(days!==1?'s':'')} • 🎟️ {n(budget)} CToken</small></>:<b>{c.previewEmpty}</b>}</div><button disabled={busy||!product||!budget} className="btn primary">{busy?c.creating:`${c.create} • ${n(budget)} CToken`}</button>{notice&&<div className="notice">{notice}</div>}</form>
 <div className="section-heading"><span>YOUR CAMPAIGNS</span><h2>{c.history}</h2></div>{error?<ErrorState error={error} onRetry={load}/>:!items.length?<div className="empty-state">{c.none}</div>:<div className="campaign-list">{items.map(x=><article className="campaign-card" key={x._id}>{x.imageUrl&&<img src={x.imageUrl} alt="" loading="lazy"/>}<div className="campaign-main"><div><span className={`status ${String(x.status).toLowerCase()}`}>{statusLabel(x.status)}</span><span className="eyebrow">{placements[x.placement]||x.placement}</span></div><h3>{x.title}</h3><p>{x.description}</p><div className="campaign-metrics"><span><BarChart3/> {n(x.impressions)} impressions</span><span><MousePointerClick/> {n(x.clicks)} clicks</span><span>🎟️ {n(x.chargedCToken)} CToken</span><span><Timer/> {new Date(x.endsAt).toLocaleString(locale)}</span></div><div className="hero-actions"><button type="button" className="small-btn" onClick={()=>view(x._id)}>{c.analytics}</button>{x.status==='ACTIVE'&&<button type="button" disabled={busy} className="small-btn danger" onClick={()=>cancel(x._id)}><XCircle size={14}/> {c.cancel}</button>}</div></div></article>)}</div>}{selected&&!analytics&&<LoadingState label="Loading analytics…"/>}{analytics&&<div className="analytics-card"><h2>{c.analytics}</h2><div className="economy-stats"><article><span>Impressions</span><b>{n(analytics.summary?.impressions)}</b></article><article><span>Clicks</span><b>{n(analytics.summary?.clicks)}</b></article><article><span>CTR</span><b>{analytics.summary?.ctr||0}%</b></article><article><span>CToken</span><b>{n(analytics.summary?.chargedCToken)}</b></article></div></div>}</section>}
