import { useEffect, useState } from 'react';
import { Landmark, RefreshCcw, WalletCards } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { botApi, botApiConfigured } from '../lib/botApi';
import { ErrorState, LoadingState } from '../components/ApiState';
import AdSlot from '../components/AdSlot';
const n=v=>Number(v||0).toLocaleString();
export default function Bank(){const {user,session}=useAuth();const [data,setData]=useState(null),[amount,setAmount]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');const token=session?.access_token;
 async function load(){if(!token)return;setError('');try{setData(await botApi.bank(token));}catch(e){setError(e)}}useEffect(()=>{load()},[token]);
 async function action(kind){const value=Math.floor(Number(amount));if(!Number.isFinite(value)||value<=0){setError(new Error('INVALID_AMOUNT'));return}setBusy(true);setError('');setNotice('');try{await (kind==='deposit'?botApi.bankDeposit(value,token):botApi.bankWithdraw(value,token));setAmount('');setNotice(kind==='deposit'?'Đã gửi CXu vào ngân hàng.':'Đã rút CXu về ví.');await load()}catch(e){setError(e)}finally{setBusy(false)}}
 if(!botApiConfigured)return <section className="section page-section"><ErrorState error="VITE_CORGI_API_URL chưa được cấu hình."/></section>;
 if(!user)return <section className="section page-section"><div className="auth-card"><Landmark/><h1>CXu Bank</h1><p>Đăng nhập Discord để quản lý CXu trong ngân hàng.</p><Link className="btn primary" to="/login">Đăng nhập</Link></div></section>;
 return <section className="section page-section"><div className="section-heading"><span>ECONOMY</span><h1>CXu Bank</h1><p>Gửi, rút và theo dõi lãi CXu trực tiếp từ tài khoản Discord của bạn.</p></div>{!data&&!error?<LoadingState/>:error?<ErrorState error={error} onRetry={load}/>:<><div className="economy-stats"><article><WalletCards/><span>Ví CXu</span><b>{n(data.walletBalance)}</b></article><article><Landmark/><span>Số dư ngân hàng</span><b>{n(data.bankBalance)}</b></article><article><RefreshCcw/><span>Lãi trọn đời</span><b>{n(data.lifetimeInterest)}</b></article><article><span>APY</span><b>{Number(data.annualRatePercent||0).toLocaleString()}%</b><small>Ghép lãi mỗi {data.compoundHours} giờ</small></article></div><div className="transaction-card"><label>Số CXu<input inputMode="numeric" min="1" value={amount} onChange={e=>setAmount(e.target.value.replace(/[^0-9]/g,''))} placeholder={`Tối thiểu ${n(data.minDeposit)}`}/></label><div className="hero-actions"><button disabled={busy} className="btn primary" onClick={()=>action('deposit')}>Gửi CXu</button><button disabled={busy} className="btn secondary" onClick={()=>action('withdraw')}>Rút CXu</button></div>{notice&&<div className="notice">{notice}</div>}{error&&<div className="notice error">{error.message}</div>}</div></>}<AdSlot placement="PROFILE"/></section>}
