import {useEffect,useState} from 'react';
import {Save,RefreshCw,Shield,Ticket,Coins,Gem,Boxes} from 'lucide-react';
import {useAuth} from '../context/AuthContext';
import {botApi} from '../lib/botApi';
const defaults={spin:{enabled:true,ticketCost:1,contributionPerTicket:100,rewards:[{cxu:100,chance:40},{cxu:250,chance:30},{cxu:500,chance:15},{cxu:1000,chance:10},{cxu:5000,chance:4},{cxu:10000,chance:1}]},eventShop:{enabled:true,redPets:[],prismaticPet:{name:'Niên Thú',price:0,stock:-1},diamondItems:[],cxuItems:[]}};
export default function Developer(){
 const {session,profile}=useAuth(),token=session?.access_token; const [cfg,setCfg]=useState(defaults),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 async function load(){setBusy(true);try{const x=await botApi.developerConfig(token);setCfg({...defaults,...x,spin:{...defaults.spin,...x?.spin},eventShop:{...defaults.eventShop,...x?.eventShop}});setNotice('')}catch(e){setNotice(e.message==='HTTP_404'||e.status===404?'⚠️ Developer API chưa được triển khai ở backend bot. Giao diện Web đã sẵn sàng.':`❌ ${e.message}`)}finally{setBusy(false)}}
 useEffect(()=>{if(token)load()},[token]);
 async function save(){setBusy(true);try{await botApi.updateDeveloperConfig(cfg,token);setNotice('✅ Đã lưu Developer configuration.')}catch(e){setNotice(`❌ ${e.message}`)}finally{setBusy(false)}}
 function reward(i,key,value){setCfg(c=>({...c,spin:{...c.spin,rewards:c.spin.rewards.map((r,n)=>n===i?{...r,[key]:Number(value)}:r)}}))}
 const total=cfg.spin.rewards.reduce((s,r)=>s+Number(r.chance||0),0);
 return <section className="page dev-page"><div className="section-head"><div><span className="eyebrow">DEVELOPER • WEB ONLY</span><h1><Shield size={30}/> Developer Control Center</h1><p>Global Corgi-Bot controls. Discord /dev is not required.</p></div><div className="dev-actions"><button className="btn secondary" onClick={load} disabled={busy}><RefreshCw size={16}/> Reload</button><button className="btn" onClick={save} disabled={busy||total!==100}><Save size={16}/> Save</button></div></div>{notice&&<div className="notice">{notice}</div>}
 <div className="dev-grid"><article className="dash-card"><h2><Ticket/> Event Spin</h2><label className="toggle-card"><input type="checkbox" checked={cfg.spin.enabled} onChange={e=>setCfg(c=>({...c,spin:{...c.spin,enabled:e.target.checked}}))}/><span><b>Spin enabled</b><small>Spin gameplay remains on Discord.</small></span></label><div className="form-grid"><label>Contribution / ticket<input type="number" value={cfg.spin.contributionPerTicket} onChange={e=>setCfg(c=>({...c,spin:{...c.spin,contributionPerTicket:Number(e.target.value)}}))}/></label><label>Tickets / spin<input type="number" min="1" value={cfg.spin.ticketCost} onChange={e=>setCfg(c=>({...c,spin:{...c.spin,ticketCost:Number(e.target.value)}}))}/></label></div><h3>CXu reward rates <span className={total===100?'rate-ok':'rate-bad'}>{total}%</span></h3><div className="rate-list">{cfg.spin.rewards.map((r,i)=><div key={i}><input type="number" value={r.cxu} onChange={e=>reward(i,'cxu',e.target.value)}/><span>CXu</span><input type="number" min="0" max="100" step="0.01" value={r.chance} onChange={e=>reward(i,'chance',e.target.value)}/><span>%</span><button className="icon-btn" onClick={()=>setCfg(c=>({...c,spin:{...c.spin,rewards:c.spin.rewards.filter((_,n)=>n!==i)}}))}>×</button></div>)}</div><button className="btn secondary" onClick={()=>setCfg(c=>({...c,spin:{...c.spin,rewards:[...c.spin.rewards,{cxu:0,chance:0}]}}))}>+ Reward tier</button></article>
 <article className="dash-card"><h2><Boxes/> Event Shop Control</h2><label className="toggle-card"><input type="checkbox" checked={cfg.eventShop.enabled} onChange={e=>setCfg(c=>({...c,eventShop:{...c.eventShop,enabled:e.target.checked}}))}/><span><b>Event Shop enabled</b><small>Web exchange only — no gameplay.</small></span></label><div className="control-summary"><div><img src="/assets/event/red-fragment.png"/><b>Red Fragment</b><span>5 Red Pets • prices/stock controlled here</span></div><div><img src="/assets/event/prismatic-fragment.png"/><b>Prismatic Fragment</b><span>Niên Thú • exclusive pet</span></div><div><img src="/assets/event/purple-diamond.png"/><b>Purple Diamond</b><span>Rare Orbs & Pet items</span></div><div><img src="/assets/event/cxu.png"/><b>CXu</b><span>Profile cosmetics & miscellaneous items</span></div></div><p className="muted">Product editor uses the backend catalog. Prices, stock, per-user limits and availability are Developer-controlled and never hard-coded by the public shop.</p></article>
 <article className="dash-card dev-wide"><h2><Gem/> Economy authority</h2><p>Developer Web is the authority for global Event economy. Server owners cannot edit Spin odds, global reward values or Event Shop pricing.</p><div className="dev-pills"><span>Spin rates</span><span>Ticket price</span><span>Shop price</span><span>Stock</span><span>Limits</span><span>Feature flags</span></div></article></div></section>;
}
