import {Building2,Fish,Gamepad2,PawPrint,Coins,Sparkles,Trophy,ShieldCheck} from 'lucide-react';
import {Link} from 'react-router-dom';
import {useI18n} from '../i18n';
const games=[
 {icon:PawPrint,vi:'Pet Hunt',en:'Pet Hunt',viD:'Săn 19 Pet thường bằng Orb. 5 Pet đặc biệt và Niên Thú không nằm trong pool săn.',enD:'Hunt 19 regular pets with Orbs. Five special pets and Nian Beast are excluded from the hunt pool.',tag:'25 PET • 19 HUNT'},
 {icon:Building2,vi:'Startup',en:'Startup',viD:'Xây công ty, phát triển nhân sự, thương hiệu, tín dụng, định giá và tiến tới IPO.',enD:'Build a company, grow staff, brand, credit and valuation, then work toward an IPO.',tag:'BUSINESS SIM'},
 {icon:Fish,vi:'Fishing',en:'Fishing',viD:'Câu cá, nâng cấp cần và mồi, quản lý kho cá và cạnh tranh bảng xếp hạng.',enD:'Fish, upgrade rods and bait, manage your catch and compete on leaderboards.',tag:'FISHING'},
 {icon:Gamepad2,vi:'Mini Games',en:'Mini Games',viD:'Liêng, Poker, Lottery và Spin được truy cập từ Game Hub trên Discord.',enD:'Liêng, Poker, Lottery and Spin are available through the Discord Game Hub.',tag:'MULTIPLAYER'},
];
export default function GameHub(){const {locale}=useI18n();const vi=locale==='vi';return <section className="section page-section gamehub-page"><div className="section-heading"><span>CORGI-BOT V10</span><h1>{vi?'Game Hub':'Game Hub'}</h1><p>{vi?'Trung tâm trò chơi của Corgi-Bot. Website giới thiệu trạng thái và hệ thống; gameplay tương tác trực tiếp diễn ra trong Discord.':'Corgi-Bot’s game center. The website presents the systems and status; interactive gameplay runs directly in Discord.'}</p></div><div className="v10-status"><div><Sparkles/><span>{vi?'Hệ sinh thái V10':'V10 Ecosystem'}</span><b>{vi?'Đang hoạt động':'Live'}</b></div><div><Coins/><span>CXu</span><b>{vi?'Kinh tế chung':'Shared Economy'}</b></div><div><Trophy/><span>{vi?'Tiến trình':'Progression'}</span><b>Profile + Ranking</b></div><div><ShieldCheck/><span>{vi?'Ngôn ngữ':'Languages'}</span><b>VI / EN</b></div></div><div className="game-system-grid">{games.map(g=>{const I=g.icon;return <article className="game-system-card" key={g.en}><div className="game-system-icon"><I/></div><span>{g.tag}</span><h2>{vi?g.vi:g.en}</h2><p>{vi?g.viD:g.enD}</p><Link className="text-link" to="/commands">{vi?'Xem lệnh liên quan →':'View related commands →'}</Link></article>})}</div><div className="callout gamehub-callout"><div><span className="eyebrow">DISCORD FIRST</span><h2>{vi?'Chơi trên Discord, theo dõi hệ sinh thái trên Web.':'Play on Discord, follow the ecosystem on the Web.'}</h2><p>{vi?'Các thao tác săn Pet, Startup và mini-game vẫn được xử lý bởi bot để dữ liệu người chơi luôn đồng bộ.':'Pet Hunt, Startup and mini-game actions remain bot-side so player data stays synchronized.'}</p></div></div></section>}
