import {useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import {BookOpen,Search,LayoutDashboard,UserRound,Store,Palette,ShieldCheck,Users,LifeBuoy,Rocket,ChevronRight} from 'lucide-react';
import {useI18n} from '../i18n/index.jsx';

const I={start:Rocket,dashboard:LayoutDashboard,profile:UserRound,market:Store,creator:Palette,clan:Users,verify:ShieldCheck,trouble:LifeBuoy};
const DATA={
 vi:{title:'Trung tâm hướng dẫn',sub:'Hướng dẫn chính thức để sử dụng Website và hệ sinh thái Corgi-Bot.',search:'Tìm hướng dẫn…',open:'Xem hướng dẫn',none:'Không tìm thấy hướng dẫn phù hợp.',back:'Quay lại tất cả',topics:{
start:['Bắt đầu',['Đăng nhập bằng Discord','Thêm Corgi-Bot vào server','Chọn server bạn quản lý','Mở Dashboard và cấu hình lần đầu']],
dashboard:['Dashboard & Modules',['Chọn server trước khi chỉnh cấu hình','Enabled nghĩa là module đang bật; Disabled nghĩa là đang tắt','Bật/tắt module chỉ áp dụng cho server đang chọn','Chọn Channel/Role phù hợp rồi lưu cấu hình']],
profile:['Profile Web',['Xem hồ sơ Discord đã liên kết','Màu chủ đạo và Bảng tên là tùy chỉnh miễn phí','Tên Discord thật không bị thay đổi khi chỉnh Bảng tên','Bấm Lưu tùy chỉnh để lưu thiết kế Profile Web']],
market:['Marketplace',['Marketplace bán Khung Avatar, Background và Danh hiệu','Mua bằng CXu; vật phẩm mua thành công được đưa vào Inventory','Màu chủ đạo và Bảng tên không phải sản phẩm Marketplace']],
creator:['Creator Studio',['Creator có thể tạo Khung Avatar, Background và Danh hiệu','Khung Avatar là vòng trang trí quanh avatar tròn; phần tâm phải thoáng/trong suốt','Background dùng tỉ lệ 9:16; Profile Bot render 900 × 1600 px','Preview sản phẩm, đặt giá CXu rồi gửi Reviewer kiểm duyệt']],
clan:['Clan Control Center',['Tạo và cấu hình Clan từ Dashboard','Quản lý thành viên, rank và đơn tham gia','Theo dõi Treasury, nhiệm vụ, event, shop, order và audit log']],
verify:['Verification & Partner',['Khu Verification quản lý yêu cầu huy hiệu','Verified và Partner là hai badge riêng và có thể cùng xuất hiện trên Profile','Trạng thái xét duyệt được quản lý bởi hệ thống Corgi-Bot']],
trouble:['Lỗi thường gặp',['Server không hiện: kiểm tra tài khoản Discord và quyền quản lý server','Không lưu được: kiểm tra đăng nhập và thử tải lại trang','Upload lỗi: kiểm tra định dạng và dung lượng file','Module không hoạt động: kiểm tra trạng thái Enabled/Disabled và cấu hình liên quan']]}},
 en:{title:'Guide Center',sub:'Official guides for the Corgi-Bot website and ecosystem.',search:'Search guides…',open:'Open guide',none:'No matching guide found.',back:'Back to all guides',topics:{start:['Getting Started',['Sign in with Discord','Add Corgi-Bot to your server','Select a server you manage','Open Dashboard and complete the initial setup']],dashboard:['Dashboard & Modules',['Select a server before changing configuration','Enabled means the module is on; Disabled means it is off','Module switches apply only to the selected server','Choose the appropriate Channel/Role and save the configuration']],profile:['Web Profile',['View your linked Discord profile','Accent Color and Nameplate are free customization','Your real Discord name is not changed by Nameplate styling','Press Save customization to store your Web Profile design']],market:['Marketplace',['Marketplace sells Avatar Frames, Backgrounds, and Titles','Buy with CXu; purchased items are added to Inventory','Accent Color and Nameplate are not Marketplace products']],creator:['Creator Studio',['Creators can make Avatar Frames, Backgrounds, and Titles','Avatar Frames decorate the circular avatar; keep the center clear/transparent','Backgrounds use 9:16; Bot Profile renders at 900 × 1600 px','Preview, set a CXu price, then submit for Reviewer approval']],clan:['Clan Control Center',['Create and configure a Clan from Dashboard','Manage members, ranks, and applications','Manage Treasury, missions, events, shop, orders, and audit log']],verify:['Verification & Partner',['Verification manages badge requests','Verified and Partner are separate badges and can appear together','Review status is managed by the Corgi-Bot system']],trouble:['Troubleshooting',['Server missing: check your Discord account and server management permission','Cannot save: verify login and reload the page','Upload error: check file format and size','Module not working: check Enabled/Disabled and related configuration']]}}
};
export default function Guide(){const {locale}=useI18n();const c=DATA[locale]||DATA.en;const [q,setQ]=useState('');const [active,setActive]=useState('');const entries=useMemo(()=>Object.entries(c.topics).filter(([,v])=>`${v[0]} ${v[1].join(' ')}`.toLowerCase().includes(q.toLowerCase())),[c,q]);const detail=active?c.topics[active]:null;return <section className="section page-section guide-page"><div className="section-heading"><span>HELP CENTER</span><h1><BookOpen size={30}/> {c.title}</h1><p>{c.sub}</p></div>{detail?<><button className="guide-back" onClick={()=>setActive('')}>← {c.back}</button><article className="guide-detail"><div className="guide-detail-icon">{(()=>{const X=I[active];return <X/>})()}</div><h2>{detail[0]}</h2><ol>{detail[1].map((x,i)=><li key={i}><b>{i+1}</b><span>{x}</span></li>)}</ol>{active==='dashboard'&&<Link className="btn primary" to="/dashboard">Dashboard <ChevronRight size={16}/></Link>}{active==='profile'&&<Link className="btn primary" to="/profile">Profile <ChevronRight size={16}/></Link>}{(active==='market'||active==='creator')&&<Link className="btn primary" to="/marketplace">Marketplace <ChevronRight size={16}/></Link>}</article></>:<><div className="guide-search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={c.search}/></div>{entries.length?<div className="guide-grid">{entries.map(([key,v])=>{const X=I[key];return <button className="guide-card" key={key} onClick={()=>setActive(key)}><span className="guide-icon"><X/></span><b>{v[0]}</b><small>{v[1][0]}</small><span className="guide-open">{c.open} <ChevronRight size={14}/></span></button>})}</div>:<div className="empty-state">{c.none}</div>}</>}</section>}
