import { useEffect, useState } from 'react';
import { Bot, Brain, ChartNoAxesCombined, Gift, ShieldCheck, Sparkles, TicketCheck, Trophy } from 'lucide-react';
import { Link } from 'react-router-dom';
import { supabase } from '../lib/supabase';
import { formatDate } from '../lib/community';
const invite=import.meta.env.VITE_DISCORD_INVITE_URL||'#';
const features=[['Quản lý máy chủ','Moderation, Auto Role, Welcome, Reaction Role và hệ thống quyền rõ ràng.',ShieldCheck],['Ticket & Support','Ticket Discord + trung tâm hỗ trợ website có lịch sử riêng.',TicketCheck],['AI Chat','Trợ lý AI tích hợp giúp thành viên hỏi đáp và tìm tính năng nhanh hơn.',Brain],['XP & Level','XP, level, rank card và bảng xếp hạng hoạt động.',ChartNoAxesCombined],['Giveaway & Poll','Giveaway, khảo sát và hoạt động cộng đồng.',Gift],['Contest Event','Submission, voting và kết quả cuộc thi.',Trophy]];
export default function Home(){const [latest,setLatest]=useState(null),[forumCount,setForumCount]=useState(0);useEffect(()=>{if(!supabase)return;(async()=>{const [{data},{count}]=await Promise.all([supabase.from('articles').select('slug,title,excerpt,published_at').eq('status','published').order('published_at',{ascending:false}).limit(1).maybeSingle(),supabase.from('forum_topics').select('*',{count:'exact',head:true})]);setLatest(data||null);setForumCount(count||0);})();},[]);return <><section className="hero section"><div className="hero-copy"><div className="eyebrow"><Sparkles size={15}/> Corgi Studio presents</div><h1>Quản lý server gọn hơn.<br/><span>Cộng đồng vui hơn.</span></h1><p>Corgi-Bot mang các công cụ quản lý, AI, level, economy, giveaway và contest vào một hệ sinh thái dễ dùng cho server Discord của bạn.</p><div className="hero-actions"><a className="btn primary" href={invite} target="_blank" rel="noreferrer"><Bot size={18}/> Thêm Corgi-Bot</a><Link className="btn secondary" to="/commands">Xem lệnh</Link></div><div className="mini-stats"><div><b>24/7</b><span>Bot online</span></div><div><b>{forumCount}</b><span>Chủ đề forum</span></div><div><b>FREE</b><span>AI cơ bản</span></div></div></div><div className="hero-panel"><div className="bot-orb"><Bot size={68}/></div><div className="status-line"><span className="dot"></span> Corgi-Bot luôn sẵn sàng đồng hành cùng server</div><div className="panel-card"><span>Cộng đồng Corgi-Bot</span><strong>Tin tức · Diễn đàn · Hỗ trợ · Thành viên</strong></div></div></section>
<section className="section"><div className="section-heading"><span>FEATURES</span><h2>Mọi thứ server cần, tập trung trong một bot.</h2></div><div className="feature-grid">{features.map(([t,d,I])=><article className="feature-card" key={t}><div className="feature-icon"><I size={22}/></div><h3>{t}</h3><p>{d}</p></article>)}</div></section>
<section className="section community-preview"><div className="section-heading"><span>COMMUNITY</span><h2>Không gian dành riêng cho cộng đồng Corgi-Bot.</h2><p>Theo dõi tin mới, tham gia thảo luận, chia sẻ ý kiến và nhận hỗ trợ khi bạn cần.</p></div><div className="community-grid"><div className="community-card"><div className="card-kicker">TIN MỚI NHẤT</div>{latest?<><h3>{latest.title}</h3><p>{latest.excerpt}</p><small className="muted">{formatDate(latest.published_at)}</small><br/><Link className="text-link" to={`/news/${latest.slug}`}>Đọc tin tức →</Link></>:<><h3>Chưa có bài viết</h3><p>Admin có thể đăng bài từ Control Panel.</p></>}</div><div className="community-card forum-cta"><div className="card-kicker">DIỄN ĐÀN</div><h3>{forumCount} chủ đề cộng đồng.</h3><p>Tạo topic, trả lời và trao đổi bằng tài khoản Discord.</p><Link className="text-link" to="/forum">Vào diễn đàn →</Link></div></div></section>
<section className="section callout"><div><span className="eyebrow">START NOW</span><h2>Sẵn sàng đưa Corgi-Bot vào server?</h2><p>Thêm bot, chạy /setup và bắt đầu cấu hình từng module.</p></div><a className="btn primary" href={invite} target="_blank" rel="noreferrer">Thêm bot vào Discord</a></section></>}
