import AdSlot from '../components/AdSlot';
import {useEffect,useState} from 'react';
import {Brain,Building2,Fish,Gamepad2,PawPrint,ShieldCheck,Sparkles,TicketCheck,Trophy} from 'lucide-react';
import {Link} from 'react-router-dom';
import {supabase} from '../lib/supabase';
import {formatDate} from '../lib/community';
import {useI18n} from '../i18n';
import BrandLogo from '../components/BrandLogo';
const invite=import.meta.env.VITE_DISCORD_INVITE_URL||'#';
const featureData=[
 ['Server Control','Quản lý Server','Moderation, Welcome, Reaction Role, Ticket và cấu hình server.','Moderation, Welcome, Reaction Roles, Tickets and server configuration.',ShieldCheck],
 ['Pet Hunt','Pet Hunt','25 Pet trong Dex: 19 Pet săn được, 5 Pet đặc biệt và 1 Pet sự kiện.','25 pets in the Dex: 19 huntable, 5 special and 1 event pet.',PawPrint],
 ['Startup','Startup','Mô phỏng công ty với nhân sự, thương hiệu, tín dụng, định giá và IPO.','Company simulation with staff, brand, credit, valuation and IPO.',Building2],
 ['Fishing','Câu cá','Câu cá, nâng cấp trang bị và cạnh tranh bảng xếp hạng.','Fishing, equipment upgrades and leaderboard competition.',Fish],
 ['Game Hub','Game Hub','Liêng, Poker, Lottery, Spin và các hệ thống game trong /game.','Liêng, Poker, Lottery, Spin and game systems inside /game.',Gamepad2],
 ['Community','Cộng đồng','Event, Clan, Creator, Marketplace, News, Forum và Mailbox.','Events, Clan, Creator, Marketplace, News, Forum and Mailbox.',Trophy],
 ['AI Chat','AI Chat','Trợ lý AI tích hợp cho thành viên Discord.','Integrated AI assistant for Discord members.',Brain],
 ['Ticket & Support','Ticket & Hỗ trợ','Ticket Discord kết hợp Support Center trên website.','Discord tickets connected with the website Support Center.',TicketCheck],
];
export default function Home(){const {t,locale}=useI18n();const vi=locale==='vi';const [latest,setLatest]=useState(null),[forumCount,setForumCount]=useState(0);useEffect(()=>{if(!supabase)return;(async()=>{const [{data},{count}]=await Promise.all([supabase.from('articles').select('slug,title,excerpt,published_at').eq('status','published').order('published_at',{ascending:false}).limit(1).maybeSingle(),supabase.from('forum_topics').select('*',{count:'exact',head:true})]);setLatest(data||null);setForumCount(count||0)})()},[]);return <><section className="hero section"><div className="hero-copy"><div className="eyebrow"><Sparkles size={15}/> {t('present')}</div><h1>{t('hero1')}<br/><span>{t('hero2')}</span></h1><p>{t('heroP')}</p><div className="hero-actions"><a className="btn primary" href={invite} target="_blank" rel="noreferrer"><BrandLogo className="button-logo"/> {t('addBot')}</a><Link className="btn secondary" to="/commands">{t('viewCommands')}</Link></div><div className="mini-stats"><div><b>24/7</b><span>{t('online')}</span></div><div><b>25</b><span>{vi?'Pet':'Pets'}</span></div><div><b>VI / EN</b><span>{t('language')}</span></div></div></div><div className="hero-panel"><div className="bot-orb"><BrandLogo/></div><div className="status-line"><span className="dot"></span> {t('ready')}</div><div className="panel-card"><span>{t('community')}</span><strong>{t('communityItems')}</strong></div></div></section><section className="section"><AdSlot placement="HOME"/></section><section className="section"><div className="section-heading"><span>{t('features')}</span><h2>{t('featuresTitle')}</h2></div><div className="feature-grid">{featureData.map(([en,viN,enD,viD,I])=><article className="feature-card" key={en}><div className="feature-icon"><I size={22}/></div><h3>{vi?viN:en}</h3><p>{vi?enD:viD}</p></article>)}</div></section><section className="section community-preview"><div className="section-heading"><span>COMMUNITY</span><h2>{t('communityTitle')}</h2><p>{t('communityP')}</p></div><div className="community-grid"><div className="community-card"><div className="card-kicker">{t('latest')}</div>{latest?<><h3>{latest.title}</h3><p>{latest.excerpt}</p><small className="muted">{formatDate(latest.published_at)}</small><br/><Link className="text-link" to={`/news/${latest.slug}`}>{t('readNews')}</Link></>:<><h3>{t('noArticle')}</h3><p>{t('adminPost')}</p></>}</div><div className="community-card forum-cta"><div className="card-kicker">{t('forumTitle')}</div><h3>{forumCount} {t('forumCount')}</h3><p>{t('forumP')}</p><Link className="text-link" to="/forum">{t('goForum')}</Link></div></div></section><section className="section callout"><div><span className="eyebrow">{t('start')}</span><h2>{t('startTitle')}</h2><p>{t('startP')}</p></div><a className="btn primary" href={invite} target="_blank" rel="noreferrer"><BrandLogo className="button-logo"/>{t('addDiscord')}</a></section></>}
