import { useEffect, useMemo, useState } from 'react';
import { Search, ShoppingBag, Tag, Check } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { botApi, botApiConfigured } from '../lib/botApi';
import { ErrorState } from '../components/ApiState';
import AdSlot from '../components/AdSlot';
import { useI18n } from '../i18n/index.jsx';
const n=v=>Number(v||0).toLocaleString();
const isUrl=v=>/^https:\/\//i.test(String(v||'').trim());
function CosmeticPreview({item={},compact=false}){const type=String(item.type||'COSMETIC').toUpperCase(),value=String(item.value||'').trim();const image=isUrl(value)?value:'';const cls=`cosmetic-preview cosmetic-${type.toLowerCase()} ${compact?'compact':''}`;if(type==='FRAME')return <div className={cls}><div className="cosmetic-avatar"><span>C</span></div>{image?<img className="cosmetic-frame-img" src={image} alt={item.name||'Frame'} loading="lazy"/>:<div className="cosmetic-frame-fallback"/>}</div>;if(type==='BACKGROUND')return <div className={cls} style={image?{backgroundImage:`linear-gradient(180deg,transparent,rgba(8,5,2,.72)),url(${image})`}:{}}><div className="cosmetic-profile-sample"><i/><span>{item.name||'Profile'}</span></div></div>;if(type==='ACCENT')return <div className={cls} style={{'--cosmetic-accent':value||'#ff9418'}}><div className="accent-swatch"/><b>Aa</b></div>;if(type==='TITLE')return <div className={cls}><span className="title-preview">{value||item.name||'TITLE'}</span></div>;if(type==='NAMEPLATE')return <div className={cls}>{image?<img src={image} alt={item.name||'Nameplate'} loading="lazy"/>:<div className="nameplate-preview">{value||item.name||'PLAYER'}</div>}</div>;if(type==='EFFECT')return <div className={cls}>{image?<img src={image} alt={item.name||'Effect'} loading="lazy"/>:<div className="effect-preview">✦ ✧ ✦</div>}</div>;return <div className={cls}><ShoppingBag/></div>}

const copy={
 vi:{title:'Marketplace',desc:'Mua bán cosmetic bằng CXu. Listing mới phải qua kiểm duyệt trước khi xuất hiện công khai.',search:'Tìm cosmetic…',empty:'Chưa có listing đang bán.',sell:'Đăng bán cosmetic',pick:'Chọn vật phẩm muốn bán',pickHint:'Chọn cosmetic trong danh mục. Hệ thống sẽ kiểm tra quyền sở hữu khi bạn gửi.',choose:'— Chọn cosmetic —',price:'Giá bán (CXu)',submit:'Gửi kiểm duyệt',sending:'Đang gửi…',buy:'Mua ngay',buying:'Đang xử lý…',login:'Đăng nhập để mua',sent:'Đã gửi listing để đội ngũ kiểm duyệt.',bought:'Mua thành công. Vật phẩm đã được chuyển vào hồ sơ của bạn.',listing:'listing'},
 en:{title:'Marketplace',desc:'Buy and sell cosmetics with CXu. New listings are reviewed before going public.',search:'Search cosmetics…',empty:'No active listings yet.',sell:'Sell a cosmetic',pick:'Choose an item to sell',pickHint:'Choose a cosmetic from the catalog. Ownership is checked when you submit.',choose:'— Choose cosmetic —',price:'Selling price (CXu)',submit:'Submit for review',sending:'Submitting…',buy:'Buy now',buying:'Processing…',login:'Log in to buy',sent:'Listing submitted for review.',bought:'Purchase complete. The item was added to your profile.',listing:'listing'},
};
export default function Marketplace(){const {locale}=useI18n();const c=copy[locale]||copy.en;const {user,session}=useAuth();const [items,setItems]=useState([]),[shop,setShop]=useState([]),[q,setQ]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(''),[form,setForm]=useState({cosmeticKey:'',price:''}),[notice,setNotice]=useState('');const token=session?.access_token;
 async function load(){setError('');try{const [marketResult,shopResult]=await Promise.allSettled([botApi.marketplace(),botApi.shop()]);if(marketResult.status==='rejected')throw marketResult.reason;setItems(marketResult.value?.items||[]);setShop(shopResult.status==='fulfilled'?(shopResult.value?.items||[]):[])}catch(e){setError(e)}}useEffect(()=>{if(botApiConfigured)load()},[]);const names=useMemo(()=>Object.fromEntries(shop.map(x=>[x.key,x])),[shop]);const filtered=items.filter(x=>{const it=names[x.cosmeticKey];return `${x.cosmeticKey} ${it?.name||''}`.toLowerCase().includes(q.toLowerCase())});
 async function buy(id){if(!token)return;setBusy(id);setNotice('');try{await botApi.marketplaceBuy(id,token);setNotice(c.bought);await load()}catch(e){setNotice(`❌ ${e.message}`)}finally{setBusy('')}}
 async function submit(e){e.preventDefault();if(!form.cosmeticKey)return;setBusy('submit');setNotice('');try{await botApi.marketplaceSubmit({cosmeticKey:form.cosmeticKey,price:Number(form.price)},token);setForm({cosmeticKey:'',price:''});setNotice(c.sent)}catch(e2){setNotice(`❌ ${e2.message}`)}finally{setBusy('')}}
 if(!botApiConfigured)return <section className="section page-section"><ErrorState error="VITE_CORGI_API_URL is not configured."/></section>;
 return <section className="section page-section"><div className="section-heading"><span>GLOBAL MARKET</span><h1>{c.title}</h1><p>{c.desc}</p></div><AdSlot placement="MARKETPLACE"/><div className="market-toolbar"><div className="search-box"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={c.search}/></div><span>{filtered.length} {c.listing}</span></div>{error?<ErrorState error={error} onRetry={load}/>:!items.length?<div className="empty-state">{c.empty}</div>:<div className="market-grid">{filtered.map(row=>{const item=names[row.cosmeticKey]||{};return <article className="market-card" key={row._id}><CosmeticPreview item={item}/><span className="eyebrow">{item.type||'COSMETIC'} • {item.rarity||'STANDARD'}</span><h3>{item.name||row.cosmeticKey}</h3><div className="market-price"><Tag size={15}/>{n(row.price)} CXu</div>{user?<button disabled={busy===row._id} className="btn primary" onClick={()=>buy(row._id)}>{busy===row._id?c.buying:c.buy}</button>:<Link className="btn secondary" to="/login">{c.login}</Link>}</article>})}</div>}{user&&<form className="panel-form market-sell" onSubmit={submit}><div className="eyebrow">SELL</div><h2>{c.sell}</h2><label>{c.pick}<small className="field-help">{c.pickHint}</small></label><div className="cosmetic-picker">{shop.map(x=><button type="button" key={x.key} className={`cosmetic-choice ${form.cosmeticKey===x.key?'selected':''}`} onClick={()=>setForm({...form,cosmeticKey:x.key})}><CosmeticPreview item={x} compact/><span><b>{x.name||x.key}</b><small>{x.type||'COSMETIC'} • {x.rarity||'STANDARD'}</small></span>{form.cosmeticKey===x.key&&<Check className="choice-check" size={18}/>}</button>)}</div><label>{c.price}<input required inputMode="numeric" min="1" value={form.price} onChange={e=>setForm({...form,price:e.target.value.replace(/[^0-9]/g,'')})} placeholder="5000"/></label><button disabled={busy==='submit'||!form.cosmeticKey||!form.price} className="btn primary">{busy==='submit'?c.sending:c.submit}</button>{notice&&<div className="notice">{notice}</div>}</form>}</section>}
