import {useEffect,useMemo,useState} from 'react';
import {Search,ShoppingBag,Tag,Upload,Palette,Image as ImageIcon,Sparkles,Type,PanelTop,Check} from 'lucide-react';
import {Link} from 'react-router-dom';
import {useAuth} from '../context/AuthContext';
import {botApi,botApiConfigured} from '../lib/botApi';
import {ErrorState} from '../components/ApiState';
import AdSlot from '../components/AdSlot';
import {useI18n} from '../i18n/index.jsx';
import {compactNumber,parseCompactNumber} from '../lib/numberFormat';
import {uploadImage} from '../lib/assetUpload';

const uploadTypes=new Set(['FRAME','BACKGROUND']);
const marketImageTypes=new Set(['FRAME','BACKGROUND','NAMEPLATE','EFFECT']);
const typeMeta={
 FRAME:{vi:'Khung Avatar',en:'Avatar Frame',icon:ImageIcon},
 BACKGROUND:{vi:'Nền Profile',en:'Profile Background',icon:PanelTop},
 ACCENT:{vi:'Màu chủ đạo',en:'Accent Color',icon:Palette},
 NAMEPLATE:{vi:'Bảng tên',en:'Nameplate',icon:Type},
 TITLE:{vi:'Danh hiệu',en:'Title',icon:Tag},
 EFFECT:{vi:'Hiệu ứng Profile',en:'Profile Effect',icon:Sparkles}
};
function typeName(type,locale){return typeMeta[type]?.[locale==='vi'?'vi':'en']||type}
function CosmeticPreview({item={},preview='',effect='sparkle',nameplate={}}){
 const type=String(item.type||'COSMETIC').toUpperCase(),value=preview||String(item.value||'').trim(),image=marketImageTypes.has(type)?value:'';
 const cls=`cosmetic-preview cosmetic-${type.toLowerCase()}`;
 if(type==='FRAME')return <div className={cls}><div className="cosmetic-avatar"><span>C</span></div>{image?<img className="cosmetic-frame-img" src={image} alt=""/>:<div className="cosmetic-frame-fallback"/>}</div>;
 if(type==='BACKGROUND')return <div className={cls} style={image?{backgroundImage:`linear-gradient(180deg,transparent,rgba(8,5,2,.72)),url(${image})`}:{}}><div className="cosmetic-profile-sample"><i/><span>{item.name||'Profile'}</span></div></div>;
 if(type==='ACCENT')return <div className={cls} style={{'--cosmetic-accent':value||'#ff9418'}}><div className="accent-swatch"/><b>Aa</b><div className="accent-lines"><i/><i/><i/></div></div>;
 if(type==='TITLE')return <div className={cls}><span className="title-preview">{value||item.name||'TITLE'}</span></div>;
 if(type==='NAMEPLATE')return <div className={cls}>{image?<img src={image} alt=""/>:<div className={`nameplate-preview ${nameplate.glow?'np-glow':''}`} style={{'--np-bg':nameplate.bg||'#241207','--np-bg2':nameplate.bg2||nameplate.bg||'#241207','--np-border':nameplate.border||'#ff9b1a','--np-text':nameplate.textColor||'#ffd27a'}}>{nameplate.text||item.name||'PLAYER'}</div>}</div>;
 if(type==='EFFECT')return <div className={`${cls} effect-${effect}`}><div className="effect-profile"><div className="effect-avatar">C</div><span>Creator</span></div><div className="effect-particles">✦ ✧ ✦</div></div>;
 return <div className={cls}><ShoppingBag/></div>;
}

const copy={
 vi:{title:'Creator Marketplace',desc:'Tạo cosmetic ngay trên web, xem trước, gửi kiểm duyệt và bán bằng CXu.',search:'Tìm cosmetic hoặc collection…',empty:'Chưa có cosmetic đang bán.',create:'Creator Studio',type:'Chọn loại sản phẩm',name:'Tên cosmetic',collection:'Tên collection',creator:'Tên Creator',asset:'Chọn ảnh từ thiết bị',price:'Giá bán (CXu)',priceHelp:'Có thể nhập 2500000 hoặc 2.5M',submit:'Gửi kiểm duyệt',sending:'Đang tải lên & gửi…',buy:'Mua ngay',buying:'Đang xử lý…',login:'Đăng nhập để mua',sent:'Đã gửi cosmetic cho Reviewer kiểm duyệt.',bought:'Mua thành công. Cosmetic đã vào Inventory.',listing:'sản phẩm',guide:'Chuẩn thiết kế Cosmetic',guideDesc:'Mỗi loại có editor và yêu cầu riêng. Preview bên dưới mô phỏng cách sản phẩm sẽ hiển thị.',backgroundHelp:'Ảnh dọc 9:16. Profile của Bot render 900 × 1600 px; khuyên dùng đúng 900 × 1600 hoặc ảnh 9:16 độ phân giải cao.',frameHelp:'PNG/WebP vuông 1:1, nền trong suốt. Giữ phần giữa thoáng để không che avatar.',accentHelp:'Không cần làm ảnh. Chọn màu trực tiếp trên Web; Bot hiện sử dụng màu HEX.',nameplateHelp:'Không cần phần mềm ngoài. Tạo bảng tên ngay tại đây rồi Web xuất thành PNG để gửi duyệt.',titleHelp:'Không cần ảnh. Nhập danh hiệu trực tiếp; preview sẽ cập nhật ngay.',effectHelp:'Editor preview hiệu ứng đã có trên Web, nhưng chưa cho gửi bán cho tới khi Profile Bot hỗ trợ EFFECT.',effectSoon:'Chưa mở bán',fileSpec:'PNG · JPG · WebP · GIF • tối đa 8 MB',preview:'Preview trực tiếp',npText:'Chữ mẫu trên bảng tên',npBg:'Màu nền',npBorder:'Màu viền',npTextColor:'Màu chữ',titleText:'Nội dung danh hiệu',accent:'Chọn màu chủ đạo',effectStyle:'Kiểu hiệu ứng',effectBlocked:'EFFECT hiện chưa được Profile Bot render. Bạn có thể thử preview, nhưng nút gửi bán được khóa để tránh bán sản phẩm không sử dụng được.',choose:'Chọn'},
 en:{title:'Creator Marketplace',desc:'Create cosmetics on the web, preview them, submit for review, and sell for CXu.',search:'Search cosmetics or collections…',empty:'No cosmetics are on sale yet.',create:'Creator Studio',type:'Choose product type',name:'Cosmetic name',collection:'Collection name',creator:'Creator name',asset:'Choose image from device',price:'Price (CXu)',priceHelp:'You can enter 2500000 or 2.5M',submit:'Submit for review',sending:'Uploading & submitting…',buy:'Buy now',buying:'Processing…',login:'Log in to buy',sent:'Cosmetic submitted for Reviewer approval.',bought:'Purchase complete. Cosmetic added to Inventory.',listing:'items',guide:'Cosmetic design specs',guideDesc:'Each type has its own editor and requirements. The preview below approximates how the product will look.',backgroundHelp:'Portrait 9:16 image. The Bot profile renders at 900 × 1600 px; use 900 × 1600 or a high-resolution 9:16 image.',frameHelp:'Square 1:1 transparent PNG/WebP. Keep the center clear so it does not cover the avatar.',accentHelp:'No image needed. Pick the color on the Web; the Bot currently uses a HEX color.',nameplateHelp:'No external editor needed. Build the nameplate here and the Web exports a PNG for review.',titleHelp:'No image needed. Enter the title directly and preview it instantly.',effectHelp:'Effect preview is available on the Web, but publishing stays disabled until the Bot profile supports EFFECT.',effectSoon:'Publishing unavailable',fileSpec:'PNG · JPG · WebP · GIF • max 8 MB',preview:'Live preview',npText:'Nameplate sample text',npBg:'Background color',npBorder:'Border color',npTextColor:'Text color',titleText:'Title text',accent:'Accent color',effectStyle:'Effect style',effectBlocked:'EFFECT is not currently rendered by the Bot profile. You can test the preview, but publishing is locked so nobody can buy an unusable product.',choose:'Choose'}
};

function nameplatePngFile(opts,name='nameplate'){
 return new Promise((resolve,reject)=>{
  const canvas=document.createElement('canvas');canvas.width=1200;canvas.height=300;const ctx=canvas.getContext('2d');
  if(!ctx)return reject(new Error('CANVAS_UNAVAILABLE'));
  const r=38,x=8,y=8,w=1184,h=284;ctx.beginPath();ctx.roundRect(x,y,w,h,r);const grad=ctx.createLinearGradient(0,0,1200,300);grad.addColorStop(0,opts.bg);grad.addColorStop(1,opts.bg2||opts.bg);ctx.fillStyle=grad;ctx.fill();ctx.lineWidth=12;ctx.strokeStyle=opts.border;if(opts.glow){ctx.shadowColor=opts.border;ctx.shadowBlur=28}ctx.stroke();ctx.shadowBlur=0;
  ctx.fillStyle=opts.textColor;ctx.font='900 86px Arial, sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';if(opts.glow){ctx.shadowColor=opts.textColor;ctx.shadowBlur=18}ctx.fillText(String(opts.text||'PLAYER').slice(0,24),600,150,1040);ctx.shadowBlur=0;
  canvas.toBlob(blob=>blob?resolve(new File([blob],`${name.replace(/[^a-z0-9-_]+/gi,'-')||'nameplate'}.png`,{type:'image/png'})):reject(new Error('NAMEPLATE_EXPORT_FAILED')),'image/png');
 });
}

export default function Marketplace(){
 const {locale}=useI18n(),c=copy[locale]||copy.en,{user,session}=useAuth(),token=session?.access_token;
 const [items,setItems]=useState([]),[q,setQ]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(''),[notice,setNotice]=useState(''),[file,setFile]=useState(null),[preview,setPreview]=useState('');
 const [form,setForm]=useState({type:'FRAME',name:'',collectionName:'',creatorName:'',value:'',price:''});
 const [nameplate,setNameplate]=useState({text:'PLAYER',bg:'#241207',bg2:'#7a2f08',border:'#ff9b1a',textColor:'#ffd27a',glow:true});const [effect,setEffect]=useState('sparkle');
 async function load(){setError('');try{setItems((await botApi.marketplace())?.items||[])}catch(e){setError(e)}}
 useEffect(()=>{if(botApiConfigured)load()},[]);useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);
 const filtered=useMemo(()=>items.filter(x=>`${x.cosmetic?.name||''} ${x.cosmetic?.collectionName||''} ${x.cosmetic?.creatorName||''}`.toLowerCase().includes(q.toLowerCase())),[items,q]);
 function chooseFile(e){const f=e.target.files?.[0]||null;setFile(f);if(preview)URL.revokeObjectURL(preview);setPreview(f?URL.createObjectURL(f):'')}
 function changeType(type){setForm(v=>({...v,type,value:type==='ACCENT'?'#ff9418':''}));setFile(null);if(preview)URL.revokeObjectURL(preview);setPreview('');setNotice('')}
 async function buy(id){if(!token)return;setBusy(id);setNotice('');try{await botApi.marketplaceBuy(id,token);setNotice(c.bought);await load()}catch(e){setNotice(`❌ ${e.message}`)}finally{setBusy('')}}
 async function submit(e){e.preventDefault();if(form.type==='EFFECT'){setNotice(`⚠️ ${c.effectBlocked}`);return}const price=parseCompactNumber(form.price);if(!Number.isFinite(price)||price<1){setNotice('❌ INVALID_PRICE');return}setBusy('submit');setNotice('');try{let value=form.value;if(uploadTypes.has(form.type))value=await uploadImage(file,'cosmetics');if(form.type==='NAMEPLATE'){const generated=await nameplatePngFile(nameplate,form.name);value=await uploadImage(generated,'cosmetics')}await botApi.creatorSubmit({...form,value,price},token);setForm({type:'FRAME',name:'',collectionName:'',creatorName:'',value:'',price:''});setFile(null);if(preview)URL.revokeObjectURL(preview);setPreview('');setNotice(c.sent)}catch(e2){setNotice(`❌ ${e2.message}`)}finally{setBusy('')}}
 const helper={FRAME:c.frameHelp,BACKGROUND:c.backgroundHelp,ACCENT:c.accentHelp,NAMEPLATE:c.nameplateHelp,TITLE:c.titleHelp,EFFECT:c.effectHelp}[form.type];
 if(!botApiConfigured)return <section className="section page-section"><ErrorState error="VITE_CORGI_API_URL is not configured."/></section>;
 return <section className="section page-section"><div className="section-heading"><span>GLOBAL CREATOR MARKET</span><h1>{c.title}</h1><p>{c.desc}</p></div><AdSlot placement="MARKETPLACE"/>
 <div className="market-toolbar"><div className="search-box"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={c.search}/></div><span>{filtered.length} {c.listing}</span></div>
 {error?<ErrorState error={error} onRetry={load}/>:!filtered.length?<div className="empty-state">{c.empty}</div>:<div className="market-grid">{filtered.map(row=>{const item=row.cosmetic||{};return <article className="market-card" key={row._id}><CosmeticPreview item={item}/><span className="eyebrow">{typeName(item.type,locale)}{item.collectionName?` • ${item.collectionName}`:''}</span><h3>{item.name||'Cosmetic'}</h3>{item.creatorName&&<p>by {item.creatorName}</p>}<div className="market-price"><Tag size={15}/>{compactNumber(row.price)} CXu</div>{user?<button disabled={busy===row._id} className="btn primary" onClick={()=>buy(row._id)}>{busy===row._id?c.buying:c.buy}</button>:<Link className="btn secondary" to="/login">{c.login}</Link>}</article>})}</div>}
 <div className="market-guide"><div className="market-guide-head"><div><span className="eyebrow">CREATOR SPECS</span><h2>{c.guide}</h2><p>{c.guideDesc}</p></div></div><div className="market-guide-grid cosmetic-guide-six">{Object.keys(typeMeta).map(type=>{const Icon=typeMeta[type].icon;const help={FRAME:c.frameHelp,BACKGROUND:c.backgroundHelp,ACCENT:c.accentHelp,NAMEPLATE:c.nameplateHelp,TITLE:c.titleHelp,EFFECT:c.effectHelp}[type];return <article className="market-example" key={type}><div className="cosmetic-guide-icon"><Icon/></div><b>{typeName(type,locale)}</b><small>{help}</small>{type==='EFFECT'&&<span className="coming-chip">{c.effectSoon}</span>}</article>})}</div><div className="market-specs"><span>{c.fileSpec}</span><span>Background: 900 × 1600 • 9:16</span><span>Frame: 1:1 • transparent</span><span>{c.preview}</span></div></div>
 {user&&<form className="panel-form market-sell creator-studio" onSubmit={submit}><div className="creator-pro-head"><div><div className="eyebrow"><Palette size={14}/> CREATOR STUDIO <span className="pro-chip">PRO</span></div><h2>{c.create}</h2><p>{locale==='vi'?'Thiết kế • Preview realtime • Xuất asset • Gửi duyệt':'Design • Realtime preview • Export asset • Submit for review'}</p></div><Sparkles className="creator-pro-spark"/></div><div className="creator-type-section"><b>{c.type}</b><div className="creator-type-grid">{Object.keys(typeMeta).map(type=>{const Icon=typeMeta[type].icon;return <button type="button" key={type} className={`creator-type-card ${form.type===type?'selected':''}`} onClick={()=>changeType(type)}><Icon size={20}/><span>{typeName(type,locale)}</span>{form.type===type&&<Check size={15}/>} {type==='EFFECT'&&<small>BETA</small>}</button>})}</div></div>
 <div className="creator-workspace"><div className="creator-fields"><div className="creator-current"><b>{typeName(form.type,locale)}</b><p>{helper}</p></div><label>{c.name}<input required maxLength="80" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>{c.collection}<input maxLength="80" value={form.collectionName} onChange={e=>setForm({...form,collectionName:e.target.value})}/></label><label>{c.creator}<input required maxLength="80" value={form.creatorName} onChange={e=>setForm({...form,creatorName:e.target.value})}/></label>
 {uploadTypes.has(form.type)&&<label className="file-upload"><span>{c.asset}</span><input required type="file" accept={form.type==='FRAME'?'image/png,image/webp':'image/png,image/jpeg,image/webp,image/gif'} onChange={chooseFile}/><span className="btn secondary"><Upload size={16}/> {file?.name||c.choose}</span><small className="field-help">{helper}</small></label>}
 {form.type==='ACCENT'&&<div className="editor-box"><label>{c.accent}<div className="color-editor"><input type="color" value={form.value||'#ff9418'} onChange={e=>setForm({...form,value:e.target.value})}/><input value={form.value||'#ff9418'} pattern="#[0-9a-fA-F]{6}" onChange={e=>setForm({...form,value:e.target.value})}/></div></label><div className="accent-presets">{['#ff9418','#64c8ff','#ff4fb3','#8b5cf6','#22d3a6','#ffd166','#ff4d4d','#f8fafc'].map(x=><button type="button" key={x} aria-label={x} style={{background:x}} className={form.value===x?'active':''} onClick={()=>setForm({...form,value:x})}/>)}</div></div>}
 {form.type==='NAMEPLATE'&&<div className="editor-box nameplate-editor"><label>{c.npText}<input maxLength="24" value={nameplate.text} onChange={e=>setNameplate({...nameplate,text:e.target.value})}/></label><div className="editor-color-grid">{[['bg',c.npBg],['bg2',locale==='vi'?'Màu gradient':'Gradient color'],['border',c.npBorder],['textColor',c.npTextColor]].map(([key,label])=><label key={key}>{label}<input type="color" value={nameplate[key]} onChange={e=>setNameplate({...nameplate,[key]:e.target.value})}/></label>)}</div><label className="creator-check"><input type="checkbox" checked={nameplate.glow} onChange={e=>setNameplate({...nameplate,glow:e.target.checked})}/><span></span>{locale==='vi'?'Bật Neon Glow':'Enable Neon Glow'}</label></div>}
 {form.type==='TITLE'&&<div className="editor-box"><label>{c.titleText}<input required maxLength="32" value={form.value} onChange={e=>setForm({...form,value:e.target.value})} placeholder="✨ Master Creator"/></label></div>}
 {form.type==='EFFECT'&&<div className="editor-box"><label>{c.effectStyle}<select value={effect} onChange={e=>setEffect(e.target.value)}><option value="sparkle">✨ Sparkle</option><option value="glow">🌌 Aura Glow</option><option value="pulse">💫 Pulse</option><option value="stars">🌟 Stars</option><option value="lightning">⚡ Lightning</option><option value="flame">🔥 Flame</option><option value="snow">❄️ Snow</option><option value="cyber">💜 Cyber Neon</option></select></label><div className="warning-box">⚠️ {c.effectBlocked}</div></div>}
 <label>{c.price}<input required inputMode="decimal" value={form.price} onChange={e=>setForm({...form,price:e.target.value})} placeholder="2.5M"/><small className="field-help">{c.priceHelp}</small></label></div>
 <aside className="creator-preview-panel"><span className="eyebrow">{c.preview}</span><CosmeticPreview item={form} preview={preview} effect={effect} nameplate={nameplate}/><small>{helper}</small></aside></div>
 <button disabled={busy==='submit'||(uploadTypes.has(form.type)&&!file)||form.type==='EFFECT'} className="btn primary creator-submit">{busy==='submit'?c.sending:form.type==='EFFECT'?c.effectSoon:c.submit}</button>{notice&&<div className="notice">{notice}</div>}</form>}
 </section>;
}
