import {useEffect,useState} from 'react';
import {LogOut,Shield,UserRound,Palette,Save} from 'lucide-react';
import {Link} from 'react-router-dom';
import {useAuth} from '../context/AuthContext';
import {supabase} from '../lib/supabase';
import {useI18n} from '../i18n/index.jsx';
const roleLabel={member:'Member',reviewer:'Reviewer',admin:'Admin',developer:'Developer'};
const defaults={accent_color:'#ff9418',nameplate_border:'#ff9b1a',nameplate_text_color:'#ffd27a',nameplate_glow:true};
export default function Profile(){const {locale}=useI18n();const vi=locale==='vi';const {user,profile,loading,signOut,refreshProfile}=useAuth();const [stats,setStats]=useState({topics:0,replies:0,comments:0,tickets:0});const [custom,setCustom]=useState(defaults);const [saving,setSaving]=useState(false);const [notice,setNotice]=useState('');
useEffect(()=>{if(!user||!supabase)return;(async()=>{const rs=await Promise.all([supabase.from('forum_topics').select('*',{count:'exact',head:true}).eq('author_id',user.id),supabase.from('forum_replies').select('*',{count:'exact',head:true}).eq('author_id',user.id),supabase.from('article_comments').select('*',{count:'exact',head:true}).eq('user_id',user.id),supabase.from('support_tickets').select('*',{count:'exact',head:true}).eq('user_id',user.id)]);setStats({topics:rs[0].count||0,replies:rs[1].count||0,comments:rs[2].count||0,tickets:rs[3].count||0});})();},[user?.id]);
useEffect(()=>{if(profile)setCustom({accent_color:profile.accent_color||defaults.accent_color,nameplate_border:profile.nameplate_border||defaults.nameplate_border,nameplate_text_color:profile.nameplate_text_color||defaults.nameplate_text_color,nameplate_glow:profile.nameplate_glow??true})},[profile]);
async function saveCustom(){if(!supabase||!user)return;setSaving(true);setNotice('');const {error}=await supabase.from('profiles').update({...custom,updated_at:new Date().toISOString()}).eq('id',user.id);if(error)setNotice(`❌ ${error.message}`);else{setNotice(vi?'✅ Đã lưu tùy chỉnh Profile Web.':'✅ Web Profile customization saved.');await refreshProfile()}setSaving(false)}
if(loading)return <section className="section page-section"><p className="muted">{vi?'Đang tải tài khoản…':'Loading account…'}</p></section>;if(!user)return <section className="section page-section"><div className="auth-card"><h1>{vi?'Chưa đăng nhập':'Not signed in'}</h1><Link className="btn primary" to="/login">{vi?'Đăng nhập':'Sign in'}</Link></div></section>;const name=profile?.display_name||'Corgi Member';const avatar=profile?.avatar_url;
return <section className="section page-section profile-page"><div className="profile-card"><div className="profile-avatar" style={{borderColor:custom.accent_color,boxShadow:`0 0 24px ${custom.accent_color}55`}}>{avatar?<img src={avatar} alt={name}/>:<UserRound size={38}/>}</div><div className="profile-main"><span className="eyebrow">{vi?'Hồ sơ cộng đồng':'Community Profile'}</span><h1>{name}</h1><p className="muted">{vi?'Tài khoản Discord đã liên kết với Corgi-Bot Community.':'Discord account linked with Corgi-Bot Community.'}</p><div className="profile-meta"><span><Shield size={15}/> {vi?'Quyền':'Role'}: <b>{roleLabel[profile?.role]||'Member'}</b></span>{profile?.discord_id&&<span>Discord ID: <code>{profile.discord_id}</code></span>}</div><div className="profile-stats"><div><b>{stats.topics}</b><span>{vi?'Chủ đề':'Topics'}</span></div><div><b>{stats.replies}</b><span>{vi?'Trả lời':'Replies'}</span></div><div><b>{stats.comments}</b><span>{vi?'Bình luận':'Comments'}</span></div><div><b>{stats.tickets}</b><span>Ticket</span></div></div><div className="profile-actions"><Link className="btn secondary" to="/bank">CXu Bank</Link><Link className="btn secondary" to="/marketplace">Marketplace</Link><Link className="btn secondary" to="/ads">CToken Ads</Link></div><button className="btn secondary" onClick={signOut}><LogOut size={17}/> {vi?'Đăng xuất':'Sign out'}</button></div></div>
<div className="profile-customizer"><div className="profile-custom-head"><div><span className="eyebrow"><Palette size={14}/> PROFILE CUSTOMIZATION</span><h2>{vi?'Tùy chỉnh Profile miễn phí':'Free Profile Customization'}</h2><p>{vi?'Màu chủ đạo và Bảng tên là tùy chỉnh cá nhân, không phải sản phẩm Marketplace.':'Accent Color and Nameplate are personal customization, not Marketplace products.'}</p></div><span className="free-chip">FREE</span></div><div className="profile-custom-grid"><div className="profile-custom-controls"><div className="custom-section"><b>{vi?'Màu chủ đạo':'Accent Color'}</b><p>{vi?'Chọn màu nhấn riêng cho Profile Web của bạn.':'Choose your Web Profile accent color.'}</p><div className="color-editor"><input type="color" value={custom.accent_color} onChange={e=>setCustom({...custom,accent_color:e.target.value})}/><input value={custom.accent_color} pattern="#[0-9a-fA-F]{6}" onChange={e=>setCustom({...custom,accent_color:e.target.value})}/></div></div><div className="custom-section"><b>{vi?'Bảng tên':'Nameplate'}</b><p>{vi?'Tên Discord thật luôn được giữ nguyên; bạn chỉ chỉnh thiết kế vùng tên.':'Your real Discord name stays unchanged; only the name area styling is customized.'}</p><div className="editor-color-grid"><label>{vi?'Màu viền':'Border'}<input type="color" value={custom.nameplate_border} onChange={e=>setCustom({...custom,nameplate_border:e.target.value})}/></label><label>{vi?'Màu chữ':'Text'}<input type="color" value={custom.nameplate_text_color} onChange={e=>setCustom({...custom,nameplate_text_color:e.target.value})}/></label></div><label className="creator-check"><input type="checkbox" checked={custom.nameplate_glow} onChange={e=>setCustom({...custom,nameplate_glow:e.target.checked})}/><span></span>{vi?'Neon Glow':'Neon Glow'}</label></div><button className="btn primary" disabled={saving} onClick={saveCustom}><Save size={16}/>{saving?(vi?'Đang lưu…':'Saving…'):(vi?'Lưu tùy chỉnh':'Save customization')}</button>{notice&&<div className="notice">{notice}</div>}</div><div className="profile-custom-preview" style={{'--profile-accent':custom.accent_color,'--np-border':custom.nameplate_border,'--np-text':custom.nameplate_text_color}}><span className="eyebrow">{vi?'PREVIEW TRỰC TIẾP':'LIVE PREVIEW'}</span><div className="web-profile-preview"><div className="web-preview-avatar">{avatar?<img src={avatar} alt=""/>:<span>C</span>}</div><div className={`web-preview-nameplate ${custom.nameplate_glow?'glow':''}`}><b>{name}</b></div><div className="web-preview-line"><i/></div><small>{vi?'Màu chủ đạo + Bảng tên':'Accent + Nameplate'}</small></div></div></div></div></section>}
