import { useEffect, useState } from 'react';
import { ExternalLink, LifeBuoy, MessageSquarePlus, Send } from 'lucide-react';
import { Link } from 'react-router-dom';
import { supabase } from '../lib/supabase';
import { useAuth } from '../context/AuthContext';
import { formatDate, profileMap } from '../lib/community';
import Avatar from '../components/Avatar';
const support=import.meta.env.VITE_SUPPORT_SERVER_URL||'#'; const topgg=import.meta.env.VITE_TOPGG_URL||'#';

export default function Support(){
 const {user,profile}=useAuth(); const [tickets,setTickets]=useState([]),[active,setActive]=useState(null),[messages,setMessages]=useState([]),[authors,setAuthors]=useState({}),[form,setForm]=useState({subject:'',category:'Hỗ trợ chung',priority:'normal',body:''}),[reply,setReply]=useState(''),[notice,setNotice]=useState('');
 async function loadTickets(){if(!user)return;const {data}=await supabase.from('support_tickets').select('*').eq('user_id',user.id).order('created_at',{ascending:false});setTickets(data||[]);}
 useEffect(()=>{loadTickets();},[user?.id]);
 async function openTicket(t){setActive(t);const {data}=await supabase.from('support_messages').select('*').eq('ticket_id',t.id).order('created_at');setMessages(data||[]);setAuthors(await profileMap((data||[]).map(x=>x.author_id)));}
 async function create(e){e.preventDefault();if(!user)return;const {data,error}=await supabase.from('support_tickets').insert({user_id:user.id,subject:form.subject.trim(),category:form.category,priority:form.priority}).select('*').single();if(error){setNotice(error.message);return;}await supabase.from('support_messages').insert({ticket_id:data.id,author_id:user.id,body:form.body.trim()});setForm({subject:'',category:'Hỗ trợ chung',priority:'normal',body:''});setNotice('Ticket đã được tạo.');await loadTickets();openTicket(data);}
 async function send(e){e.preventDefault();if(!reply.trim()||!active)return;const {data,error}=await supabase.from('support_messages').insert({ticket_id:active.id,author_id:user.id,body:reply.trim()}).select('*').single();if(!error){setMessages(v=>[...v,data]);setAuthors(v=>({...v,[user.id]:profile}));setReply('');}}
 return <section className="section page-section"><div className="section-heading"><span>SUPPORT</span><h1>Trung tâm hỗ trợ</h1><p>Ticket website được lưu riêng theo tài khoản Discord; chỉ bạn và đội ngũ quản trị có thể xem.</p></div>
 <div className="support-grid external-support"><a className="support-card" href={support} target="_blank" rel="noreferrer"><LifeBuoy size={28}/><div><b>Discord Support</b><span>Nhận hỗ trợ trực tiếp</span></div><ExternalLink size={18}/></a><a className="support-card" href={topgg} target="_blank" rel="noreferrer"><span className="topgg-mark">TOP</span><div><b>Top.gg</b><span>Xem trang bot và đánh giá</span></div><ExternalLink size={18}/></a></div>
 {!user?<div className="auth-card compact-card"><h2>Đăng nhập để mở ticket</h2><p>Mỗi ticket được gắn với tài khoản Discord của bạn.</p><Link className="btn primary" to="/login">Đăng nhập Discord</Link></div>:<div className="ticket-layout"><div><form className="panel-form" onSubmit={create}><div className="eyebrow"><MessageSquarePlus size={15}/> NEW TICKET</div><h2>Tạo yêu cầu hỗ trợ</h2><label>Tiêu đề<input required minLength={4} maxLength={180} value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/></label><div className="form-grid"><label>Danh mục<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Hỗ trợ chung</option><option>Báo lỗi</option><option>Premium</option><option>Thiết lập bot</option></select></label><label>Mức độ<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option value="low">Thấp</option><option value="normal">Bình thường</option><option value="high">Cao</option></select></label></div><label>Nội dung<textarea required rows="5" value={form.body} onChange={e=>setForm({...form,body:e.target.value})}/></label><button className="btn primary">Tạo ticket</button>{notice&&<p className="muted">{notice}</p>}</form><div className="ticket-list"><h3>Ticket của bạn</h3>{tickets.map(t=><button className={`ticket-item ${active?.id===t.id?'active':''}`} onClick={()=>openTicket(t)} key={t.id}><div><b>{t.subject}</b><span>{formatDate(t.created_at)}</span></div><em className={`status ${t.status}`}>{t.status}</em></button>)}</div></div>
 <div className="ticket-thread">{active?<><div className="thread-head"><div><span className="eyebrow">#{active.id.slice(0,8)}</span><h2>{active.subject}</h2></div><span className={`status ${active.status}`}>{active.status}</span></div><div className="message-list">{messages.map(m=><article className="ticket-message" key={m.id}><Avatar profile={authors[m.author_id]|| (m.author_id===user.id?profile:null)} size={38}/><div><div className="comment-head"><strong>{authors[m.author_id]?.display_name||(m.author_id===user.id?profile?.display_name:'Staff')}</strong><span>{formatDate(m.created_at)}</span></div><p>{m.body}</p></div></article>)}</div>{active.status!=='closed'&&<form className="reply-form" onSubmit={send}><textarea rows="3" value={reply} onChange={e=>setReply(e.target.value)} placeholder="Trả lời ticket…"/><button className="btn primary"><Send size={16}/> Gửi</button></form>}</>:<div className="empty-state">Chọn một ticket để xem cuộc hội thoại.</div>}</div></div>}
 </section>;
}
