import { NavLink } from 'react-router-dom';
import { BadgeDollarSign, Crown, HelpCircle, Home, Landmark, Megaphone, Menu, Terminal, X, Newspaper, MessagesSquare, Info, LogIn, UserRound, ShieldCog, Store, Languages } from 'lucide-react';
import { useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { roleAtLeast } from '../lib/community';
import {localeNames,locales,useI18n} from '../i18n';
import BrandLogo from './BrandLogo';
const invite = import.meta.env.VITE_DISCORD_INVITE_URL || '#';
export default function Layout({ children }) {
 const [open,setOpen]=useState(false); const {user,profile}=useAuth(); const {locale,setLocale,t}=useI18n();
 const nav=[['/',t('home'),Home],['/commands',t('commands'),Terminal],['/news',t('news'),Newspaper],['/forum',t('forum'),MessagesSquare],['/bank','CXu Bank',Landmark],['/marketplace','Marketplace',Store],['/ads','CToken Ads',Megaphone],['/premium','Premium',Crown],['/support',t('support'),HelpCircle]];
 const accountLabel=profile?.display_name||user?.user_metadata?.name||t('profile');
 return <div className="site-shell"><header className="topbar"><NavLink to="/" className="brand" onClick={()=>setOpen(false)}><div className="brand-mark"><BrandLogo/></div><div><strong>Corgi-Bot</strong><span>{t('official')}</span></div></NavLink><nav className={`nav ${open?'open':''}`}>{nav.map(([to,label,Icon])=><NavLink key={to} to={to} end={to==='/'} onClick={()=>setOpen(false)}><Icon size={17}/>{label}</NavLink>)}{roleAtLeast(profile?.role,'reviewer')&&<NavLink to="/marketplace/review" onClick={()=>setOpen(false)}><ShieldCog size={17}/>{t('review')}</NavLink>}{roleAtLeast(profile?.role,'admin')&&<NavLink to="/admin" onClick={()=>setOpen(false)}><ShieldCog size={17}/>{t('admin')}</NavLink>}<NavLink className="account-link" to={user?'/profile':'/login'} onClick={()=>setOpen(false)}>{user?<UserRound size={17}/>:<LogIn size={17}/>} {user?accountLabel:t('login')}</NavLink><label className="language-picker"><Languages size={16}/><select aria-label={t('language')} value={locale} onChange={e=>setLocale(e.target.value)}>{locales.map(x=><option key={x} value={x}>{localeNames[x]}</option>)}</select></label><a className="invite-small" href={invite} target="_blank" rel="noreferrer"><BadgeDollarSign size={16}/> {t('addBot')}</a></nav><button className="menu-btn" onClick={()=>setOpen(!open)} aria-label="Menu">{open?<X/>:<Menu/>}</button></header><main>{children}</main><footer className="footer"><div className="footer-brand"><BrandLogo/><div><strong>Corgi-Bot</strong><p>{t('footer')}</p></div></div><div className="footer-links"><NavLink to="/about"><Info size={14}/> {t('about')}</NavLink><NavLink to="/terms">{t('terms')}</NavLink><NavLink to="/privacy">{t('privacy')}</NavLink></div><span>© 2026 Corgi Studio</span></footer></div>
}
