import {useEffect,useMemo,useState} from 'react';
import {ShoppingBag,X} from 'lucide-react';
import {Link} from 'react-router-dom';
import {useAuth} from '../context/AuthContext';
import {botApi} from '../lib/botApi';
const tabs=[['red','Mảnh Ghép Đỏ','/assets/event/red-fragment.png'],['prismatic','Mảnh Ngũ Sắc','/assets/event/prismatic-fragment.png'],['contribution','Điểm Cống Hiến','/assets/event/purple-diamond.png'],['cxu','CXu','/assets/event/cxu.png'],['eventTicket','Vé Sự Kiện','/assets/event/event-ticket.png']];
const chests=[['bronze','Rương Đồng',1,10000,'/assets/event/chest-bronze.png'],['silver','Rương Bạc',2,100000,'/assets/event/chest-silver.png'],['gold','Rương Vàng',3,1000000,'/assets/event/chest-gold.png'],['diamond','Rương Kim Cương',5,10000000,'/assets/event/chest-diamond.png'],['legendary','Rương Huyền Thoại',7,100000000,'/assets/event/chest-legendary.png']];
const Img=({src,alt=''})=><img src={src} alt={alt} onError={e=>{e.currentTarget.style.display='none';e.currentTarget.parentElement?.classList.add('asset-missing')}}/>;
export default function EventShop(){
 const {session}=useAuth(),token=session?.access_token,[data,setData]=useState({wallet:{},items:[],ticketOffer:null}),[tab,setTab]=useState('red'),[notice,setNotice]=useState(''),[selected,setSelected]=useState(null);
 async function load(){try{setData(await botApi.eventShop(token))}catch(e){setNotice(`⚠️ ${e.message}`)}}
 useEffect(()=>{if(token)load()},[token]);
 const items=useMemo(()=>(data.items||[]).filter(x=>x.currency===tab),[data,tab]);
 const currency=tabs.find(t=>t[0]===tab)?.[1];
 async function buy(id){try{await botApi.eventShopExchange(id,token);setNotice('✅ Đổi thưởng thành công.');setSelected(null);load()}catch(e){setNotice(`❌ ${e.message}`)}}
 async function ticket(){try{await botApi.eventTicketBuy(1,token);setNotice('✅ Đã mua 1 Vé Quay Thưởng.');load()}catch(e){setNotice(`❌ ${e.message}`)}}
 async function chest(tier){try{const r=await botApi.eventChestOpen(tier,token);setNotice(`🎁 Mở rương thành công: +${Number(r.cxu).toLocaleString()} CXu`);setSelected(null);load()}catch(e){setNotice(`❌ ${e.message}`)}}
 if(!token)return <section className="page"><h1>Event Shop</h1><p>Đăng nhập Discord để xem tài nguyên và đổi thưởng.</p></section>;
 return <section className="page event-shop-page"><div className="section-head"><div><span className="eyebrow">REWARD EXCHANGE • WEBSITE EVENT HUB</span><h1><ShoppingBag/> Cửa hàng Sự kiện</h1><p>Đổi tài nguyên và nhận thưởng. Các thiết lập được quản lý bởi Đội Ngũ Quản Trị.</p></div></div>{notice&&<div className="notice">{notice}</div>}
 <div className="event-wallet">{tabs.slice(0,4).map(([k,n,img])=><div key={k}><Img src={img}/><span>{n}</span><b>{data.wallet?.[k]??0}</b></div>)}<div><Img src="/assets/event/lucky-ticket.png"/><span>Vé Quay Thưởng</span><b>{data.wallet?.luckyTickets??0}</b></div><div><Img src="/assets/event/event-ticket.png"/><span>Vé Sự Kiện</span><b>{data.wallet?.eventTickets??0}</b></div></div>
 <div className="event-action-row"><article className="ticket-booth"><Img src="/assets/event/lucky-ticket.png"/><div><b>Vé Quay Thưởng</b><p>1.000 Điểm Cống Hiến / vé.</p></div><button className="btn" onClick={ticket}>Mua 1 vé</button></article><Link className="ticket-booth spin-entry" to="/spin-wheel"><Img src="/assets/event/lucky-ticket.png"/><div><b>🎡 Vòng Quay Thưởng</b><p>Vào page riêng để quay và quản lý Kho Tạm.</p></div><strong>Chơi ngay →</strong></Link></div>
 <div className="event-tabs">{tabs.map(([k,n,img])=><button className={tab===k?'active':''} key={k} onClick={()=>setTab(k)}><Img src={img}/>{n}</button>)}</div>
 {tab==='eventTicket'?<div className="event-product-grid chest-grid">{chests.map(([tier,n,cost,max,img])=><button type="button" className="event-product compact-product" key={tier} onClick={()=>setSelected({kind:'chest',tier,name:n,cost,max,image:img})}><div className="event-product-art"><Img src={img}/></div><h3>{n}</h3><b>{cost} Vé Sự Kiện</b><span className="product-more">Xem chi tiết →</span></button>)}</div>:<div className="event-product-grid">{items.length?items.map(x=><button type="button" className="event-product compact-product" key={x.id} onClick={()=>setSelected({kind:'item',...x})}><div className="event-product-art"><Img src={x.image||tabs.find(t=>t[0]===tab)?.[2]}/></div><h3>{x.name}</h3><b>{x.price} {currency}</b><span className="product-more">Xem chi tiết →</span></button>):<div className="dash-card"><b>Chưa có sản phẩm.</b><p>Đội Ngũ Quản Trị sẽ cập nhật sản phẩm tại đây.</p></div>}</div>}
 {selected&&<div className="shop-detail-overlay" onClick={()=>setSelected(null)}><article className="shop-detail" onClick={e=>e.stopPropagation()}><button className="shop-detail-close" onClick={()=>setSelected(null)} aria-label="Đóng"><X/></button><div className="shop-detail-art"><Img src={selected.image}/></div><h2>{selected.name}</h2>{selected.kind==='chest'?<><p>Giải CXu cao nhất: <b>{selected.max.toLocaleString()} CXu</b>. Mốc cao nhất có tỷ lệ rất hiếm.</p><div className="shop-detail-meta"><b>{selected.cost} Vé Sự Kiện</b><span>Nhận vé qua Tournament</span></div><button className="btn primary" onClick={()=>chest(selected.tier)}>Mở rương</button></>:<><p>{selected.description||'Vật phẩm đổi thưởng trong Cửa hàng Sự kiện.'}</p><div className="shop-detail-meta"><b>{selected.price} {currency}</b><span>{selected.stock<0?'Không giới hạn':`Còn ${selected.stock}`}</span></div><button className="btn primary" onClick={()=>buy(selected.id)}>Đổi thưởng</button></>}</article></div>}
 </section>
}
